export enum PermitStatus {
  APPROVED = 'APPROVED',
  AUTO_APPROVED = 'AUTO_APPROVED',
  CANCELLED = 'CANCELLED',
  IN_PROGRESS = 'IN_PROGRESS',
  ISSUED = 'ISSUED',
  REJECTED = 'REJECTED',
  REVOKED = 'REVOKED',
  SUPERSEDED = 'SUPERSEDED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VOIDED = 'VOIDED',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
}
