export enum UserAuthGroup {
  ANONYMOUS = 'ANONYMOUS',
  CV_CLIENT = 'CVCLIENT',
  COMPANY_ADMINISTRATOR = 'ORGADMIN',
  PPC_CLERK = 'PPCCLERK',
  PPC_SUPERVISOR = 'CTPO',
  PUBLIC_VERIFIED = 'PUBLIC',
  SYSTEM_ADMINISTRATOR = 'SYSADMIN',
  ENFORCEMENT_OFFICER = 'EOFFICER',
  HQ_ADMINISTRATOR = 'HQADMIN',
  FINANCE = 'FINANCE',
}
