---
version: "3.8"

services:
  postgres-db:
    container_name: postgres-db
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: postgres-db
    image: postgres:13
    restart: always
    volumes:
      - /pgdata

  sql-server-db:
    container_name: sql-server-db
    build:
      context: ./database/mssql
      dockerfile: Dockerfile
    environment:
      MSSQL_HOST: ${MSSQL_HOST}
      MSSQL_PORT: ${MSSQL_PORT}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_SA_USER: ${MSSQL_SA_USER}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_ENCRYPT: ${MSSQL_ENCRYPT}
      MSSQL_INIT_DDL_FILENAME: ${MSSQL_INIT_DDL_FILENAME}
      MSSQL_RUN_TESTS: ${MSSQL_RUN_TESTS}
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S $$MSSQL_HOST -U $$MSSQL_SA_USER -P $$MSSQL_SA_PASSWORD -Q "USE $$MSSQL_DB" | grep "Changed database context to '$$MSSQL_DB'"
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: sql-server-db
    ports:
      - "1433:1433"
    volumes:
      - /sql_data

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DB_TYPE: mssql
      POSTGRESQL_HOST: postgres-db
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
      MSSQL_HOST: sql-server-db
      MSSQL_PORT: 1433
      MSSQL_DB: ORBC_DEV
      MSSQL_SA_USER: SA
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_ENCRYPT: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      sql-server-db:
        condition: service_healthy
    hostname: backend
    links:
      - sql-server-db
      - postgres-db
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        VITE_DEPLOY_ENVIRONMENT: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: frontend
    links:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
