---
version: "3.8"

services:
  database:
    container_name: database
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: database
    image: postgres:13
    restart: always
    volumes:
      - /pgdata

  sql-server-db:
    container_name: sql-server-db
    build:
      context: ./database/mssql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - /sql_data

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        POSTGRESQL_HOST: database
        POSTGRESQL_USER: default
        POSTGRESQL_PASSWORD: default
        POSTGRESQL_DATABASE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: backend
    links:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:z
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        VITE_DEPLOY_ENVIRONMENT: prod
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
