---
version: "3.8"

services:
  postgres-db:
    container_name: postgres-db
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: postgres-db
    image: postgres:13
    restart: always
    volumes:
      - /pgdata

  sql-server-db:
    container_name: sql-server-db
    env_file:
      - /database/.env
    build:
      context: ./database/mssql
      dockerfile: Dockerfile
      args:
        MSSQL_HOST: ${MSSQL_HOST:-localhost}
        MSSQL_PORT: ${MSSQL_PORT:-1433}
        MSSQL_DB: ${MSSQL_DB:-onroutebc}
        MSSQL_SA_USER: ${MSSQL_SA_USER:-SA}
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}
        MSSQL_ENCRYPT: ${MSSQL_ENCRYPT:-false}
    hostname: sql-server-db
    ports:
      - "${MSSQL_PORT:-1433}:${MSSQL_PORT:-1433}"
    volumes:
      - /sql_data

  backend:
    container_name: backend
    env_file:
      - /backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        DB_TYPE: ${DB_TYPE:-mssql}
        POSTGRESQL_HOST: database
        POSTGRESQL_USER: default
        POSTGRESQL_PASSWORD: default
        POSTGRESQL_DATABASE: default
        MSSQL_HOST: ${MSSQL_HOST:-localhost}
        MSSQL_PORT: ${MSSQL_PORT:-1433}
        MSSQL_DB: ${MSSQL_DB:-onroutebc}
        MSSQL_SA_USER: ${MSSQL_SA_USER:-SA}
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}
        MSSQL_ENCRYPT: ${MSSQL_ENCRYPT:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: backend
    links:
      - postgres-db
      - sql-server-db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:z
      - /app/node_modules

  frontend:
    container_name: frontend
    env_file:
      - /frontend/.env
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: frontend
    links:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
