SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO
IF NOT EXISTS (SELECT 1 FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE = N'TRCKPME')
BEGIN
INSERT INTO dbo.ORBC_POWER_UNIT_TYPE
  (POWER_UNIT_TYPE, TYPE, DESCRIPTION, IS_ACTIVE)
  VALUES
  ('TRCKPME', 'Truck with PME', 'Truck with PME', 1);
END
GO


IF @@ERROR <> 0 SET NOEXEC ON
GO
IF NOT EXISTS (SELECT 1 FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE = N'TRACPME')
BEGIN
INSERT INTO dbo.ORBC_POWER_UNIT_TYPE
  (POWER_UNIT_TYPE, TYPE, DESCRIPTION, IS_ACTIVE)
  VALUES
  ('TRACPME', 'Truck Tractor with PME', 'Truck Tractor with PME', 1);
END
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Add TRCKPME and TRACPME to ORBC_POWER_UNIT_TYPE table'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE])
VALUES (101, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
