SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update status of any IDIRBASIC IDIR users to ANONYMOUS (should be none)
UPDATE dbo.ORBC_IDIR_USER
SET USER_AUTH_GROUP_TYPE = 'ANONYMOUS'
WHERE USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Update status of any IDIRBASIC non-staff users to ANONYMOUS (should be none)
UPDATE dbo.ORBC_USER
SET USER_AUTH_GROUP_TYPE = 'ANONYMOUS'
WHERE USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Delete all group role mappings for IDIRBASIC
DELETE
FROM access.ORBC_GROUP_ROLE
WHERE USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Delete IDIRBASIC group
DELETE
FROM access.ORBC_USER_AUTH_GROUP_TYPE
WHERE USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Remove unused IDIRBASIC auth group'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (17, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO

