USE $(MSSQL_DB)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION
CREATE TABLE [dbo].[ORBC_SYS_VERSION](
	[MIGRATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[VERSION_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
	[DDL_FILE_SHA1] [varchar](40) NULL,
	[RELEASE_DATE] [datetime2](7) NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_SYS_VERSION] PRIMARY KEY CLUSTERED 
(
	[MIGRATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORBC_SYS_VERSION] ADD  CONSTRAINT [DF_ORBC_SYS_VERSION_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO

ALTER TABLE [dbo].[ORBC_SYS_VERSION] ADD  CONSTRAINT [DF_ORBC_SYS_VERSION_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO

ALTER TABLE [dbo].[ORBC_SYS_VERSION] ADD  CONSTRAINT [DF_ORBC_SYS_VERSION_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO

ALTER TABLE [dbo].[ORBC_SYS_VERSION] ADD  CONSTRAINT [DF_ORBC_SYS_VERSION_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Initialize versions system table'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES ($(VERSION_ID), @VersionDescription, '$(FILE_HASH)', getdate())

COMMIT