SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Add new auth groups
INSERT [access].[ORBC_USER_AUTH_GROUP_TYPE] ([USER_AUTH_GROUP_TYPE], [DISPLAY_NAME], [DESCRIPTION], [STAFF_FLAG], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PAPPLICANT', N'Permit Applicant', N'Commercial Vehicle client allowed to apply for permits', 0, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

UPDATE [access].[ORBC_GROUP_ROLE] SET USER_AUTH_GROUP_TYPE ='PAPPLICANT', DB_LAST_UPDATE_TIMESTAMP = GETUTCDATE() WHERE  USER_AUTH_GROUP_TYPE='CVCLIENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

UPDATE [dbo].[ORBC_USER] SET USER_AUTH_GROUP_TYPE ='PAPPLICANT', DB_LAST_UPDATE_TIMESTAMP = GETUTCDATE() WHERE  USER_AUTH_GROUP_TYPE='CVCLIENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

UPDATE [dbo].[ORBC_COMPANY_USER] SET USER_AUTH_GROUP_TYPE ='PAPPLICANT', DB_LAST_UPDATE_TIMESTAMP = GETUTCDATE() WHERE  USER_AUTH_GROUP_TYPE='CVCLIENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

UPDATE [dbo].[ORBC_PENDING_USER] SET USER_AUTH_GROUP_TYPE ='PAPPLICANT', DB_LAST_UPDATE_TIMESTAMP = GETUTCDATE() WHERE  USER_AUTH_GROUP_TYPE='CVCLIENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

DELETE FROM [access].[ORBC_USER_AUTH_GROUP_TYPE] WHERE USER_AUTH_GROUP_TYPE='CVCLIENT'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO


DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Rename CVCLIENT to PAPPLICANT'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (23, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
