SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

--------------------------------------
-- Policy configuration table creation
--------------------------------------
CREATE TABLE [dbo].[ORBC_POLICY_CONFIGURATION](
	[POLICY_CONFIGURATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[POLICY_JSON] [nvarchar](max) NULL,
	[EFFECTIVE_DATE] [datetime2](7) NULL,
	[IS_DRAFT] [char](1) NULL,
	[CHANGE_DESCRIPTION] [nvarchar](2000) NULL,
	[APP_CREATE_TIMESTAMP] [datetime2](7) NULL,
	[APP_CREATE_USERID] [nvarchar](30) NULL,
	[APP_CREATE_USER_GUID] [char](32) NULL,
	[APP_CREATE_USER_DIRECTORY] [nvarchar](30) NULL,
	[APP_LAST_UPDATE_TIMESTAMP] [datetime2](7) NULL,
	[APP_LAST_UPDATE_USER_GUID] [char](32) NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY] [nvarchar](30) NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_POLICY_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[POLICY_CONFIGURATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION] ADD  CONSTRAINT [DF_ORBC_POLICY_CONFIGURATION_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO

ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION] ADD  CONSTRAINT [DF_ORBC_POLICY_CONFIGURATION_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO

ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION] ADD  CONSTRAINT [DF_ORBC_POLICY_CONFIGURATION_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO

ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION] ADD  CONSTRAINT [DF_ORBC_POLICY_CONFIGURATION_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created by the application.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_CREATE_TIMESTAMP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The userid of the application user that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_CREATE_USERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The guid of the application user that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_CREATE_USER_GUID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The directory of the application user that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_CREATE_USER_DIRECTORY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was last updated by the application.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_LAST_UPDATE_TIMESTAMP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The guid of the application user that last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_LAST_UPDATE_USER_GUID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The directory of the application user that last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'APP_LAST_UPDATE_USER_DIRECTORY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POLICY_CONFIGURATION', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

--------------------------------------
-- Policy configuration history objects
--------------------------------------
CREATE SEQUENCE [dbo].[ORBC_POLICY_CONFIGURATION_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [dbo].[ORBC_POLICY_CONFIGURATION_HIST](
  _POLICY_CONFIGURATION_HIST_ID [bigint] DEFAULT (NEXT VALUE FOR [dbo].[ORBC_POLICY_CONFIGURATION_H_ID_SEQ]) NOT NULL
  ,EFFECTIVE_DATE_HIST [datetime] NOT NULL default getutcdate()
  ,END_DATE_HIST [datetime]
  , [POLICY_CONFIGURATION_ID] int NOT NULL, [EFFECTIVE_DATE] datetime2 NULL, [IS_DRAFT] char(1) NULL, [CHANGE_DESCRIPTION] nvarchar(2000) NULL, [APP_CREATE_TIMESTAMP] datetime2 NULL, [APP_CREATE_USERID] nvarchar(30) NULL, [APP_CREATE_USER_GUID] char(32) NULL, [APP_CREATE_USER_DIRECTORY] nvarchar(30) NULL, [APP_LAST_UPDATE_TIMESTAMP] datetime2 NULL, [APP_LAST_UPDATE_USER_GUID] char(32) NULL, [APP_LAST_UPDATE_USER_DIRECTORY] nvarchar(30) NULL, [CONCURRENCY_CONTROL_NUMBER] int NULL, [DB_CREATE_USERID] varchar(63) NOT NULL, [DB_CREATE_TIMESTAMP] datetime2 NOT NULL, [DB_LAST_UPDATE_USERID] varchar(63) NOT NULL, [DB_LAST_UPDATE_TIMESTAMP] datetime2 NOT NULL
  )
ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION_HIST] ADD CONSTRAINT ORBC_18_H_PK PRIMARY KEY CLUSTERED (_POLICY_CONFIGURATION_HIST_ID);  
ALTER TABLE [dbo].[ORBC_POLICY_CONFIGURATION_HIST] ADD CONSTRAINT ORBC_18_H_UK UNIQUE (_POLICY_CONFIGURATION_HIST_ID,END_DATE_HIST)
go

CREATE TRIGGER ORBC_POLCFG_A_S_IUD_TR ON [dbo].[ORBC_POLICY_CONFIGURATION] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [dbo].[ORBC_POLICY_CONFIGURATION_HIST] set END_DATE_HIST = @curr_date where POLICY_CONFIGURATION_ID in (select POLICY_CONFIGURATION_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [dbo].[ORBC_POLICY_CONFIGURATION_HIST] ([POLICY_CONFIGURATION_ID], [EFFECTIVE_DATE], [IS_DRAFT], [CHANGE_DESCRIPTION], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _POLICY_CONFIGURATION_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [POLICY_CONFIGURATION_ID], [EFFECTIVE_DATE], [IS_DRAFT], [CHANGE_DESCRIPTION], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [dbo].[ORBC_POLICY_CONFIGURATION_H_ID_SEQ]) as [_POLICY_CONFIGURATION_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

--------------------------------------
-- History objects for database version 27
--------------------------------------
CREATE SEQUENCE [permit].[ORBC_CFS_TRANSACTION_DETAIL_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST](
  _CFS_TRANSACTION_DETAIL_HIST_ID [bigint] DEFAULT (NEXT VALUE FOR [permit].[ORBC_CFS_TRANSACTION_DETAIL_H_ID_SEQ]) NOT NULL
  ,EFFECTIVE_DATE_HIST [datetime] NOT NULL default getutcdate()
  ,END_DATE_HIST [datetime]
  , [ID] bigint NOT NULL, [TRANSACTION_ID] bigint NOT NULL, [FILE_NAME] nchar(30) NULL, [CFS_FILE_STATUS_TYPE] varchar(10) NOT NULL, [ERROR_MESSAGE] nvarchar(3000) NULL, [PROCESSSING_DATE_TIME] datetime NULL, [CONCURRENCY_CONTROL_NUMBER] int NULL, [DB_CREATE_USERID] varchar(63) NULL, [DB_CREATE_TIMESTAMP] datetime2 NULL, [DB_LAST_UPDATE_USERID] varchar(63) NULL, [DB_LAST_UPDATE_TIMESTAMP] datetime2 NULL
  )
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] ADD CONSTRAINT ORBC_2_H_PK PRIMARY KEY CLUSTERED (_CFS_TRANSACTION_DETAIL_HIST_ID);  
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] ADD CONSTRAINT ORBC_2_H_UK UNIQUE (_CFS_TRANSACTION_DETAIL_HIST_ID,END_DATE_HIST)
go

CREATE TRIGGER ORBC_CFSTRDT_A_S_IUD_TR ON [permit].[ORBC_CFS_TRANSACTION_DETAIL] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] set END_DATE_HIST = @curr_date where ID in (select ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] ([ID], [TRANSACTION_ID], [FILE_NAME], [CFS_FILE_STATUS_TYPE], [ERROR_MESSAGE], [PROCESSSING_DATE_TIME], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _CFS_TRANSACTION_DETAIL_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [ID], [TRANSACTION_ID], [FILE_NAME], [CFS_FILE_STATUS_TYPE], [ERROR_MESSAGE], [PROCESSSING_DATE_TIME], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [permit].[ORBC_CFS_TRANSACTION_DETAIL_H_ID_SEQ]) as [_CFS_TRANSACTION_DETAIL_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

--------------------------------------
-- History objects for database version 28
--------------------------------------
CREATE SEQUENCE [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST](
  _CREDIT_ACCOUNT_ACTIVITY_HIST_ID [bigint] DEFAULT (NEXT VALUE FOR [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_H_ID_SEQ]) NOT NULL
  ,EFFECTIVE_DATE_HIST [datetime] NOT NULL default getutcdate()
  ,END_DATE_HIST [datetime]
  , [ACTIVITY_ID] int NOT NULL, [CREDIT_ACCOUNT_ID] int NOT NULL, [IDIR_USER_GUID] char(32) NOT NULL, [DATE] datetime2 NOT NULL, [CREDIT_ACCOUNT_ACTIVITY_TYPE] nvarchar(10) NOT NULL, [COMMENTS] nvarchar(4000) NULL, [CONCURRENCY_CONTROL_NUMBER] int NULL, [APP_CREATE_TIMESTAMP] datetime2 NULL, [APP_CREATE_USERID] nvarchar(30) NULL, [APP_CREATE_USER_GUID] char(32) NULL, [APP_CREATE_USER_DIRECTORY] nvarchar(30) NULL, [APP_LAST_UPDATE_TIMESTAMP] datetime2 NULL, [APP_LAST_UPDATE_USERID] nvarchar(30) NULL, [APP_LAST_UPDATE_USER_GUID] char(32) NULL, [APP_LAST_UPDATE_USER_DIRECTORY] nvarchar(30) NULL, [DB_CREATE_USERID] varchar(63) NULL, [DB_CREATE_TIMESTAMP] datetime2 NULL, [DB_LAST_UPDATE_USERID] varchar(63) NULL, [DB_LAST_UPDATE_TIMESTAMP] datetime2 NULL
  )
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST] ADD CONSTRAINT ORBC_8_H_PK PRIMARY KEY CLUSTERED (_CREDIT_ACCOUNT_ACTIVITY_HIST_ID);  
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST] ADD CONSTRAINT ORBC_8_H_UK UNIQUE (_CREDIT_ACCOUNT_ACTIVITY_HIST_ID,END_DATE_HIST)
go

CREATE TRIGGER ORBC_CRACCACT_A_S_IUD_TR ON [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST] set END_DATE_HIST = @curr_date where ACTIVITY_ID in (select ACTIVITY_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST] ([ACTIVITY_ID], [CREDIT_ACCOUNT_ID], [IDIR_USER_GUID], [DATE], [CREDIT_ACCOUNT_ACTIVITY_TYPE], [COMMENTS], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _CREDIT_ACCOUNT_ACTIVITY_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [ACTIVITY_ID], [CREDIT_ACCOUNT_ID], [IDIR_USER_GUID], [DATE], [CREDIT_ACCOUNT_ACTIVITY_TYPE], [COMMENTS], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_H_ID_SEQ]) as [_CREDIT_ACCOUNT_ACTIVITY_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

CREATE SEQUENCE [permit].[ORBC_CREDIT_ACCOUNT_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [permit].[ORBC_CREDIT_ACCOUNT_HIST](
  _CREDIT_ACCOUNT_HIST_ID [bigint] DEFAULT (NEXT VALUE FOR [permit].[ORBC_CREDIT_ACCOUNT_H_ID_SEQ]) NOT NULL
  ,EFFECTIVE_DATE_HIST [datetime] NOT NULL default getutcdate()
  ,END_DATE_HIST [datetime]
  , [CREDIT_ACCOUNT_ID] int NOT NULL, [COMPANY_ID] int NOT NULL, [CREDIT_ACCOUNT_STATUS_TYPE] nvarchar(10) NOT NULL, [CREDIT_ACCOUNT_TYPE] nvarchar(10) NOT NULL, [CFS_PARTY_NUMBER] int NOT NULL, [CREDIT_ACCOUNT_NUMBER] nvarchar(6) NOT NULL, [CFS_SITE_NUMBER] int NULL, [CONCURRENCY_CONTROL_NUMBER] int NULL, [APP_CREATE_TIMESTAMP] datetime2 NULL, [APP_CREATE_USERID] nvarchar(30) NULL, [APP_CREATE_USER_GUID] char(32) NULL, [APP_CREATE_USER_DIRECTORY] nvarchar(30) NULL, [APP_LAST_UPDATE_TIMESTAMP] datetime2 NULL, [APP_LAST_UPDATE_USERID] nvarchar(30) NULL, [APP_LAST_UPDATE_USER_GUID] char(32) NULL, [APP_LAST_UPDATE_USER_DIRECTORY] nvarchar(30) NULL, [DB_CREATE_USERID] varchar(63) NULL, [DB_CREATE_TIMESTAMP] datetime2 NULL, [DB_LAST_UPDATE_USERID] varchar(63) NULL, [DB_LAST_UPDATE_TIMESTAMP] datetime2 NULL
  )
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_HIST] ADD CONSTRAINT ORBC_7_H_PK PRIMARY KEY CLUSTERED (_CREDIT_ACCOUNT_HIST_ID);  
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_HIST] ADD CONSTRAINT ORBC_7_H_UK UNIQUE (_CREDIT_ACCOUNT_HIST_ID,END_DATE_HIST)
go

CREATE TRIGGER ORBC_CRACC_A_S_IUD_TR ON [permit].[ORBC_CREDIT_ACCOUNT] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [permit].[ORBC_CREDIT_ACCOUNT_HIST] set END_DATE_HIST = @curr_date where CREDIT_ACCOUNT_ID in (select CREDIT_ACCOUNT_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [permit].[ORBC_CREDIT_ACCOUNT_HIST] ([CREDIT_ACCOUNT_ID], [COMPANY_ID], [CREDIT_ACCOUNT_STATUS_TYPE], [CREDIT_ACCOUNT_TYPE], [CFS_PARTY_NUMBER], [CREDIT_ACCOUNT_NUMBER], [CFS_SITE_NUMBER], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _CREDIT_ACCOUNT_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [CREDIT_ACCOUNT_ID], [COMPANY_ID], [CREDIT_ACCOUNT_STATUS_TYPE], [CREDIT_ACCOUNT_TYPE], [CFS_PARTY_NUMBER], [CREDIT_ACCOUNT_NUMBER], [CFS_SITE_NUMBER], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [permit].[ORBC_CREDIT_ACCOUNT_H_ID_SEQ]) as [_CREDIT_ACCOUNT_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

CREATE SEQUENCE [permit].[ORBC_CREDIT_ACCOUNT_USER_H_ID_SEQ] AS [bigint] START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 50;

CREATE TABLE [permit].[ORBC_CREDIT_ACCOUNT_USER_HIST](
  _CREDIT_ACCOUNT_USER_HIST_ID [bigint] DEFAULT (NEXT VALUE FOR [permit].[ORBC_CREDIT_ACCOUNT_USER_H_ID_SEQ]) NOT NULL
  ,EFFECTIVE_DATE_HIST [datetime] NOT NULL default getutcdate()
  ,END_DATE_HIST [datetime]
  , [CREDIT_ACCOUNT_USER_ID] int NOT NULL, [COMPANY_ID] int NOT NULL, [CREDIT_ACCOUNT_ID] int NOT NULL, [IS_ACTIVE] char(1) NOT NULL, [APP_CREATE_TIMESTAMP] datetime2 NULL, [APP_CREATE_USERID] nvarchar(30) NULL, [APP_CREATE_USER_GUID] char(32) NULL, [APP_CREATE_USER_DIRECTORY] nvarchar(30) NULL, [APP_LAST_UPDATE_TIMESTAMP] datetime2 NULL, [APP_LAST_UPDATE_USERID] nvarchar(30) NULL, [APP_LAST_UPDATE_USER_GUID] char(32) NULL, [APP_LAST_UPDATE_USER_DIRECTORY] nvarchar(30) NULL, [CONCURRENCY_CONTROL_NUMBER] int NULL, [DB_CREATE_USERID] varchar(63) NOT NULL, [DB_CREATE_TIMESTAMP] datetime2 NOT NULL, [DB_LAST_UPDATE_USERID] varchar(63) NOT NULL, [DB_LAST_UPDATE_TIMESTAMP] datetime2 NOT NULL
  )
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_USER_HIST] ADD CONSTRAINT ORBC_9_H_PK PRIMARY KEY CLUSTERED (_CREDIT_ACCOUNT_USER_HIST_ID);  
ALTER TABLE [permit].[ORBC_CREDIT_ACCOUNT_USER_HIST] ADD CONSTRAINT ORBC_9_H_UK UNIQUE (_CREDIT_ACCOUNT_USER_HIST_ID,END_DATE_HIST)
go

CREATE TRIGGER ORBC_CRACCUSR_A_S_IUD_TR ON [permit].[ORBC_CREDIT_ACCOUNT_USER] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [permit].[ORBC_CREDIT_ACCOUNT_USER_HIST] set END_DATE_HIST = @curr_date where CREDIT_ACCOUNT_USER_ID in (select CREDIT_ACCOUNT_USER_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [permit].[ORBC_CREDIT_ACCOUNT_USER_HIST] ([CREDIT_ACCOUNT_USER_ID], [COMPANY_ID], [CREDIT_ACCOUNT_ID], [IS_ACTIVE], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _CREDIT_ACCOUNT_USER_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [CREDIT_ACCOUNT_USER_ID], [COMPANY_ID], [CREDIT_ACCOUNT_ID], [IS_ACTIVE], [APP_CREATE_TIMESTAMP], [APP_CREATE_USERID], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [permit].[ORBC_CREDIT_ACCOUNT_USER_H_ID_SEQ]) as [_CREDIT_ACCOUNT_USER_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Policy configuration table creation plus history tables for v28 and v27'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (29, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
