SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

CREATE TABLE [dbo].[ORBC_POWER_UNIT](
	[POWER_UNIT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNIT_NUMBER] [nvarchar](10) NULL,
	[PLATE] [nvarchar](10) NOT NULL,
	[PROVINCE_ID] [char](5) NOT NULL,
	[YEAR] [smallint] NOT NULL,
	[MAKE] [nvarchar](50) NOT NULL,
	[VIN] [char](6) NOT NULL,
	[LICENSED_GVW] [numeric](18, 2) NULL,
	[POWER_UNIT_TYPE_CODE] [char](7) NOT NULL,
	[STEER_AXLE_TIRE_SIZE] [int] NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_POWER_UNIT] PRIMARY KEY CLUSTERED 
(
	[POWER_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORBC_TRAILER](
	[TRAILER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNIT_NUMBER] [nvarchar](10) NULL,
	[PLATE] [nvarchar](10) NOT NULL,
	[PROVINCE_ID] [char](5) NOT NULL,
	[YEAR] [smallint] NOT NULL,
	[MAKE] [nvarchar](50) NOT NULL,
	[VIN] [char](6) NOT NULL,
	[TRAILER_TYPE_CODE] [char](7) NOT NULL,
	[EMPTY_TRAILER_WIDTH] [numeric](18, 2) NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_TRAILER] PRIMARY KEY CLUSTERED 
(
	[TRAILER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORBC_VT_COUNTRY](
	[COUNTRY_CODE] [char](2) NOT NULL,
	[COUNTRY_NAME] [varchar](50) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_VT_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[COUNTRY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE](
	[TYPE_CODE] [char](7) NOT NULL,
	[TYPE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[SORT_ORDER] [int] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_VT_POWER_UNIT_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORBC_VT_PROVINCE](
	[PROVINCE_ID] [char](5) NOT NULL,
	[PROVINCE_CODE] [char](2) NOT NULL,
	[PROVINCE_NAME] [nvarchar](100) NOT NULL,
	[COUNTRY_CODE] [char](2) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_VT_PROVINCE_ID] PRIMARY KEY CLUSTERED 
(
	[PROVINCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORBC_VT_TRAILER_TYPE](
	[TYPE_CODE] [char](7) NOT NULL,
	[TYPE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[SORT_ORDER] [int] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_VT_TRAILER_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ORBC_VT_COUNTRY] ([COUNTRY_CODE], [COUNTRY_NAME], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA', N'Canada', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_COUNTRY] ([COUNTRY_CODE], [COUNTRY_NAME], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'MX', N'Mexico', 3, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_COUNTRY] ([COUNTRY_CODE], [COUNTRY_NAME], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US', N'United States', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_COUNTRY] ([COUNTRY_CODE], [COUNTRY_NAME], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'XX', N'Others', 99, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE());
GO
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BUSCRUM', N'Buses/Crummies', N'A motor vehicle used to transport persons, when such transportation is not undertaken for compensation or gain.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BUSTRLR', N'Intercity Buses (Pulling Pony Trailers)', N'Intercity Buses are vehicles designed to carry more than 15 passengers and equipped with facilities to allow extended travel without stopping.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CONCRET', N'Concrete Pumper Trucks', N'Concrete Pumper Trucks are used to pump concrete from a cement mixer truck to where the concrete is actually needed. They travel on the highway at their equipped weight with no load.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CRAFTAT', N'Cranes, Rubber-Tired Loaders, Firetrucks - All Terrain', N'Industrial vehicles not designed to transport load on highways.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CRAFTMB', N'Cranes, Rubber-Tired Loaders, Firetrucks - Mobile', N'Industrial vehicles not designed to transport load on highways.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'DDCKBUS', N'Double Decker Buses', N'Double Decker buses are used primarily by the tourism industry.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FARMVEH', N'Farm Vehicles', N'A Farm Vehicle is a commercial vehicle owned and operated by a farmer, rancher or market gardener, the use of which is confined to purposes connected with his farm, ranch or market garden, including use for pleasure and is not used in connection with any other business in which the owner may be engaged.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'GRADERS', N'Fixed Equipment - Trucks/Graders etc.', N'Fixed Equipment means equipment bolted or welded to the truck or trailer, which was designed to perform certain engineered function(s), e.g. drilling derrick, vacuum bag house, and coil rig, etc., and may or may not include some incidental reducible load required for the intended function of the vehicle (such as the coil tubing in a coil tubing unit).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LCVRMDB', N'Long Combination Vehicles (LCV) - Rocky Mountain Doubles', N'LCV vehicles for approved carriers and routes only.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LCVTPDB', N'Long Combination Vehicles (LCV) - Turnpike Doubles', N'LCV vehicles for approved carriers and routes only.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGGING', N'Logging Trucks', N'Logging Truck is a truck or truck and trailer combination used to haul, in their natural state, green felled or bucked logs or poles.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGOFFH', N'Logging Trucks - Off-Highway', N'Logging Trucks - Off-Highway are permitted on an occasional basis from manufacturers to/from customers and to/from the bush for repairs etc., at maximum dimensions noted in Policy.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LWBTRCT', N'Long Wheelbase Truck Tractors Exceeding 6.2 m up to 7.25 m', N'Long Wheelbase Truck Tractors Exceeding 6.2 m up to 7.25 are vehicles that do not comply with wheelbase requirements indicated in CTR Appendix B', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'OGBEDTK', N'Oil and Gas - Bed Trucks', N'Bed Truck means a truck tractor equipped with a cargo carrying deck and a winch that is used for self loading and that is located behind the cab.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'OGOILSW', N'Oil and Gas - Oilfield Sows', N'Oil and Gas - Oilfield Sows are vehicles that are exceptionally large truck-tractors equipped with a cargo carrying deck and winch located behind the cab used for loading and unloading in the oilfield.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'OGSERVC', N'Oil and Gas - Service Rigs', N'Oil and Gas - Service Rigs are fixed equipment oilfield service trucks and includes rathole augers only equiped with heavy front projected crane (must exceed 14,000 kg tare weight).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'OGSRRAH', N'Oil and Gas - Service Rigs and Rathole Augers Only Equipped with Heavy Front Projected Crane (must exceed 14,000 kg tare weight)', N'Oil and Gas - Service Rigs are fixed equipment oilfield service trucks and includes rathole augers only equiped with heavy front projected crane (must exceed 14,000 kg tare weight).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PICKRTT', N'Picker Truck Tractors', N'Picker Truck Tractors is a heavy duty crane mounted on a truck tractor or truck, considered permanently mounted equipment.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PLOWBLD', N'Trucks Equipped with Front or Underbody Plow Blades', N'Vehicles not covered by the Highway Maintenance Agreement may be permitted to a width of 3.2 m.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'REGTRCK', N'Trucks', N'A Truck is a motor vehicle, other than a bus, that is either permanently fitted with special equipment or is designed to and normally used to carry a load, and that may operate as a single unit or may pull a full trailer or pony trailer.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'SCRAPER', N'Scrapers', N'A Scraper is a vehicle that is designed and used primarily for grading of highways, earth moving and other construction work on highways and that is not designed or used primarily for the transportation of persons or property, and that is only incidentally operated or moved over a highway.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'SPAUTHV', N'Specially Authorized Vehicles', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STINGER', N'Truck Tractors - Stinger Steered', N'Truck Tractors - Stinger Steered are vehicles equipped with a rear mounted underslung fifth wheel and are considered a truck tractor similar to an auto carrier;', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'TOWVEHC', N'Tow Vehicles', N'Tow Vehicles means a motor vehicle used exclusively for towing or rendering assistance to other motor vehicles or to vehicles suffering from defects or disability in their means of locomotion.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'TRKTRAC', N'Truck Tractors', N'Truck Tractor is a motor vehicle, having a net weight of more than 4,000 kg, that is equipped with a fifth-wheel coupler or a centre rotatable log bunk mounted on a bolster affixed to the vehicles chassis, and includes an auto carrier with an underslung fifth wheel coupler and a truck tractor with a load box.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PUTAXIS', N'Taxis', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-AB', N'AB', N'Alberta', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-BC', N'BC', N'British Columbia', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-MB', N'MB', N'Manitoba', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-NB', N'NB', N'New Brunswick', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-NL', N'NL', N'Newfoundland and Labrador', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-NS', N'NS', N'Nova Scotia', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-NT', N'NT', N'Northwest Territories', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-NU', N'NU', N'Nunavut', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-ON', N'ON', N'Ontario', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-PE', N'PE', N'Prince Edward Island', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-QC', N'QC', N'Quebec', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-SK', N'SK', N'Saskatchewan', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'CA-YT', N'YT', N'Yukon', N'CA', 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-AK', N'AK', N'Alaska', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-AL', N'AL', N'Alabama', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-AR', N'AR', N'Arkansas', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-AZ', N'AZ', N'Arizona', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-CA', N'CA', N'California', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-CO', N'CO', N'Colorado', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-CT', N'CT', N'Connecticut', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-DC', N'DC', N'District of Columbia', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-DE', N'DE', N'Delaware', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-FL', N'FL', N'Florida', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-GA', N'GA', N'Georgia', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-HI', N'HI', N'Hawaii', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-IA', N'IA', N'Iowa', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-ID', N'ID', N'Idaho', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-IL', N'IL', N'Illinois', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-IN', N'IN', N'Indiana', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-KS', N'KS', N'Kansas', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-KY', N'KY', N'Kentucky', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-LA', N'LA', N'Louisiana', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MA', N'MA', N'Massachusetts', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MD', N'MD', N'Maryland', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-ME', N'ME', N'Maine', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MI', N'MI', N'Michigan', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MN', N'MN', N'Minnesota', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MO', N'MO', N'Missouri', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MS', N'MS', N'Mississippi', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-MT', N'MT', N'Montana', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NC', N'NC', N'North Carolina', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-ND', N'ND', N'North Dakota', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NE', N'NE', N'Nebraska', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NH', N'NH', N'New Hampshire', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NJ', N'NJ', N'New Jersey', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NM', N'NM', N'New Mexico', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NV', N'NV', N'Nevada', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-NY', N'NY', N'New York', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-OH', N'OH', N'Ohio', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-OK', N'OK', N'Oklahoma', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-OR', N'OR', N'Oregon', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-PA', N'PA', N'Pennsylvania', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-RI', N'RI', N'Rhode Island', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-SC', N'SC', N'South Carolina', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-SD', N'SD', N'South Dakota', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-TN', N'TN', N'Tennessee', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-TX', N'TX', N'Texas', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-UT', N'UT', N'Utah', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-VA', N'VA', N'Virginia', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-VT', N'VT', N'Vermont', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-WA', N'WA', N'Washington', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-WI', N'WI', N'Wisconsin', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-WV', N'WV', N'West Virginia', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'US-WY', N'WY', N'Wyoming', N'US', 2, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'MX-XX', N'XX', N'Others', N'MX', 3, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID], [PROVINCE_CODE], [PROVINCE_NAME], [COUNTRY_CODE], [SORT_ORDER], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'XX-XX', N'XX', N'Others', N'XX', 99, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BOOSTER', N'Boosters', N'A Booster is similar to a jeep, but it is used behind a load.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'DBTRBTR', N'Tandem/Tridem Drive B-Train (Super B-Train)', N'B-trains for wood chip residual.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'DOLLIES', N'Dollies', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'EXPANDO', N'Expando Semi-Trailers', N'For use with Oil Field Bed Truck as power unit only. For other applications use Semi Trailer - Highboy or step deck, lowbed, expandos.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FEBGHSE', N'Fixed Equipment - Portable Asphalt Baghouses', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
--INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FECVYPT', N'Fixed Equipment - Conveyors (Pony Trailers)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
--INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FECVYST', N'Fixed Equipment - Conveyors (Semi-Trailers)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FECVYER', N'Fixed Equipment - Conveyors', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FEDRMMX', N'Fixed Equipment - Counter Flow Asphalt Drum Mixers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FEPNYTR', N'Fixed Equipment - Pony Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FESEMTR', N'Fixed Equipment - Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FEWHELR', N'Fixed Equipment - Wheeler Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FLOATTR', N'Float Trailers', N'See Commercial Transport Procedures Manual chapter 4.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'FULLLTL', N'Full Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'HIBOEXP', N'Semi-Trailers - Hiboys/Expandos', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'HIBOFLT', N'Semi-Trailers - Hiboys/Flat Decks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'JEEPSRG', N'Jeeps', N'Jeep means a semi-trailer that is designed to be attached between a truck tractor and another semi-trailer, so as to distribute the load of the other semi-trailer between the axles of the jeep and axles of the truck tractor.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGDGLG', N'Legacy Logging Trailer Combinations - Tandem Pole Trailers, Dogloggers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGFULL', N'Logging Trailers - Full Trailers, Tri Axle, Quad Axle', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGNTAC', N'Legacy Logging Trailer Combinations - Non-TAC B-Trains', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGOWBK', N'Logging Trailers - Overwidth Bunks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGSMEM', N'Logging Semi-Trailer - Empty, 3.2 m Bunks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGTNDM', N'Legacy Logging Trailer Combinations - Single Axle Jeeps, Tandem Axle Pole Trailers, Dogloggers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'LOGTRIX', N'Legacy Logging Trailer Combinations - Single Axle Jeeps, Tri Axle Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'ODTRLEX', N'Overdimensional Trailers and Semi-Trailers (For Export)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'OGOSFDT', N'Oil and Gas - Oversize Oilfield Flat Deck Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PLATFRM', N'Platform Trailers', N'Extraordinary Loads Only (currently platform trailers require extraordinary load approval).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'POLETRL', N'Pole Trailers', N'CTR Appendices H and I – plus legacy vehicles from 5.3.7.C including doglogger and sjostrom trailer.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PONYTRL', N'Pony Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'REDIMIX', N'Ready Mix Concrete Pump Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'SEMITRL', N'Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'SPAUTHV', N'Specially Authorized Vehicles', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STACTRN', N'Semi-Trailers - A-Trains and C-Trains', N'A-Train means a combination of vehicles composed of a truck tractor, a semi-trailer and either, (a) an A dolly and a semi-trailer, or (b) a full trailer.    C-Train means a combination of vehicles composed of a truck tractor and a semi-trailer, followed by another semi-trailer attached to the first semi-trailer by the means of a C dolly or C converter dolly.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STBTRAN', N'Semi-Trailers - B-Trains', N'B-trains for transporting reducible or non reducible loads other than wood chip residual.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STCHIPS', N'Semi-Trailers - Walled B-Trains (Chip Trucks)', N'See Commercial Transport Procedures Manual chapter 4.5.1 for details', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STCRANE', N'Semi-Trailers with Crane', N'See commercial transport procedures manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STLOGNG', N'Semi-Trailers - Logging', N'See Commercial Transport Procedures Manual chapter 4.5 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STNTSHC', N'Semi-Trailers - Non-Tac Short Chassis', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STREEFR', N'Semi-Trailers - Insulated Vans with Reefer/Refrigeration Units', N'See commercial transport procedures manual chapter 5.1 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STROPRT', N'Steering Trailers - Manned', N'Treated as a semi-trailer axle group and a booster in the Heavy Haul Quick Reference Chart, but with a requirement that the number of axles in the frst axle group cannot exceed the number of axles in the second axle group.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STRSELF', N'Steering Trailers - Self/Remote', N'Treated as a semi-trailer axle group and a booster in the Heavy Haul Quick Reference Chart, but with a requirement that the number of axles in the first axle group cannot exceed the number of axles in the second axle group.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STSDBDK', N'Semi-Trailers - Single Drop, Double Drop, Step Decks, Lowbed, Expandos, etc.', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STSTEER', N'Semi-Trailers - Steering Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STSTNGR', N'Semi-Trailers - Stinger Steered Automobile Transporters', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STWDTAN', N'Semi-Trailers - Spread Tandems', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STWHELR', N'Semi-Trailers - Wheelers', N'Note that at this time, wheeler semi-trailers need extraordinary load approvals except on the pre-approved wheeler 85 tonne routes from 6.3.3.D (different from the other 85 tonne routes)).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STWIDWH', N'Semi-Trailers - Wide Wheelers', N'Extraordinary Loads Only (currently wide wheelers require extraordinary load approval).', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'XXXXXXX', N'None', N'Select "None" if no trailer is required and only the power unit is being permitted.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'MHMBSHL', N'Manufactured Homes, Modular Buildings, Structures and Houseboats (<= 5.0 m OAW) with Attached Axles', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'MHMBSHG', N'Manufactured Homes, Modular Buildings, Structures and Houseboats (> 5.0 m OAW) with Attached Axles', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PMHWAAX', N'Park Model Homes with Attached Axles', N'', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
INSERT [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE], [TYPE], [DESCRIPTION], [SORT_ORDER], [IS_ACTIVE], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STINGAT', N'Stinger Steered Automobile Transporters', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', NULL, 1, NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] ADD  CONSTRAINT [DF_ORBC_POWER_UNIT_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] ADD  CONSTRAINT [DF_ORBC_POWER_UNIT_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] ADD  CONSTRAINT [DF_ORBC_POWER_UNIT_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] ADD  CONSTRAINT [DF_ORBC_POWER_UNIT_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_TRAILER] ADD  CONSTRAINT [DF_ORBC_TRAILER_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_TRAILER] ADD  CONSTRAINT [DF_ORBC_TRAILER_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_TRAILER] ADD  CONSTRAINT [DF_ORBC_TRAILER_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_TRAILER] ADD  CONSTRAINT [DF_ORBC_TRAILER_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_COUNTRY] ADD  CONSTRAINT [DF_ORBC_VT_COUNTRY_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_COUNTRY] ADD  CONSTRAINT [DF_ORBC_VT_COUNTRY_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_COUNTRY] ADD  CONSTRAINT [DF_ORBC_VT_COUNTRY_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_COUNTRY] ADD  CONSTRAINT [DF_ORBC_VT_COUNTRY_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_POWER_UNIT_TYPE_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_POWER_UNIT_TYPE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_POWER_UNIT_TYPE_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_POWER_UNIT_TYPE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_POWER_UNIT_TYPE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_PROVINCE] ADD  CONSTRAINT [DF_ORBC_VT_PROVINCE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_PROVINCE] ADD  CONSTRAINT [DF_ORBC_VT_PROVINCE_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_PROVINCE] ADD  CONSTRAINT [DF_ORBC_VT_PROVINCE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_PROVINCE] ADD  CONSTRAINT [DF_ORBC_VT_PROVINCE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_TRAILER_TYPE_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[ORBC_VT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_TRAILER_TYPE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_TRAILER_TYPE_DB_CREATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_VT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_TRAILER_TYPE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORBC_VT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORBC_VT_TRAILER_TYPE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getutcdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_POWER_UNIT_POWER_UNIT_TYPE] FOREIGN KEY([POWER_UNIT_TYPE_CODE])
REFERENCES [dbo].[ORBC_VT_POWER_UNIT_TYPE] ([TYPE_CODE])
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] CHECK CONSTRAINT [FK_ORBC_POWER_UNIT_POWER_UNIT_TYPE]
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_POWER_UNIT_PROVINCE] FOREIGN KEY([PROVINCE_ID])
REFERENCES [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID])
GO
ALTER TABLE [dbo].[ORBC_POWER_UNIT] CHECK CONSTRAINT [FK_ORBC_POWER_UNIT_PROVINCE]
GO
ALTER TABLE [dbo].[ORBC_TRAILER]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_TRAILER_PROVINCE] FOREIGN KEY([PROVINCE_ID])
REFERENCES [dbo].[ORBC_VT_PROVINCE] ([PROVINCE_ID])
GO
ALTER TABLE [dbo].[ORBC_TRAILER] CHECK CONSTRAINT [FK_ORBC_TRAILER_PROVINCE]
GO
ALTER TABLE [dbo].[ORBC_TRAILER]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_TRAILER_TRAILER_TYPE] FOREIGN KEY([TRAILER_TYPE_CODE])
REFERENCES [dbo].[ORBC_VT_TRAILER_TYPE] ([TYPE_CODE])
GO
ALTER TABLE [dbo].[ORBC_TRAILER] CHECK CONSTRAINT [FK_ORBC_TRAILER_TRAILER_TYPE]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique identifier for this vehicle record in a company inventory.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'POWER_UNIT_ID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Number or code that the company uses to refer to the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'UNIT_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'License plate.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'PLATE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canadian province or US state of registration of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'PROVINCE_ID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Year of manufacture of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'YEAR'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Make (manufacturer) of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'MAKE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Short vehicle identification number (last 6 characters) for the power unit.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'VIN'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Licensed gross vehicle weight of the power unit.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'LICENSED_GVW'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Type of the power unit.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'POWER_UNIT_TYPE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Size of the steer axle tires (width).' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'STEER_AXLE_TIRE_SIZE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Represents a power unit added to a company''s vehicle inventory.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_POWER_UNIT'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique identifier for this vehicle record in a company inventory.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'TRAILER_ID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Number or code that the company uses to refer to the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'UNIT_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'License plate.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'PLATE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canadian province or US state of registration of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'PROVINCE_ID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Year of manufacture of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'YEAR'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Make (manufacturer) of the vehicle.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'MAKE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Short vehicle identification number (last 6 characters) for the trailer.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'VIN'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Type of the trailer.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'TRAILER_TYPE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Width in metres of the empty trailer.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'EMPTY_TRAILER_WIDTH'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Represents a trailer added to a company''s vehicle inventory.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_TRAILER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique country identifier.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'COUNTRY_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Common name of the country.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'COUNTRY_NAME'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Order that the country should be displayed in user interfaces.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'SORT_ORDER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A lookup table of countries to be presented in dropdown lists etc.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_COUNTRY'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique identifier of the power unit type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'TYPE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Short description of the power unit type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'TYPE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Long description of the power unit type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'DESCRIPTION'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Order that the type should be presented in user interfaces.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'SORT_ORDER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the power unit type is currently active in onRouteBC - 1 indicates yes, 0 indicates no.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'IS_ACTIVE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Lookup table containing all valid types of power unit in ORBC' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_POWER_UNIT_TYPE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique ID of the province/state and country combination' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'PROVINCE_ID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'2-character short code for the Canadian province or US state.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'PROVINCE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Common name of the Canadian province or US state.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'PROVINCE_NAME'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Country in which the province or state is a jurisdiction (Canada or USA).' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'COUNTRY_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Order that the province or state should be displayed in user interfaces.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'SORT_ORDER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Lookup table containing all valid canadian provinces, us states, and other countries available to the ORBC application' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_PROVINCE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unique identifier of the trailer type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'TYPE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Short description of the trailer type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'TYPE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Long description of the trailer type.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'DESCRIPTION'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Order that the type should be presented in user interfaces.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'SORT_ORDER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the trailer type is currently active in onRouteBC - 1 indicates yes, 0 indicates no.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'IS_ACTIVE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application code is responsible for retrieving the row and then incrementing the value of the CONCURRENCY_CONTROL_NUMBER column by one prior to issuing an update. If this is done then the update will succeed, provided that the row was not updated by any other transactions in the period between the read and the update operations.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'CONCURRENCY_CONTROL_NUMBER'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'DB_CREATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The user or proxy account that created or last updated the record.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_USERID'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The date and time the record was created or last updated.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE', @level2type=N'COLUMN',@level2name=N'DB_LAST_UPDATE_TIMESTAMP'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Lookup table containing all valid types of trailer in ORBC' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ORBC_VT_TRAILER_TYPE'
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Initial creation of schema entities for manage vehicles feature'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (2, @VersionDescription, '$(FILE_HASH)', getutcdate())

COMMIT