SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

IF @@ERROR <> 0
   SET NOEXEC ON
GO

ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] DROP CONSTRAINT [FK_ORBC_SPECIAL_AUTH_NO_FEE_TYPE]

ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] DROP CONSTRAINT [PK_ORBC_NO_FEE_TYPE]

ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] ALTER COLUMN NO_FEE_TYPE VARCHAR(16) NOT NULL

ALTER TABLE [permit].[ORBC_SPECIAL_AUTH_HIST] ALTER COLUMN NO_FEE_TYPE VARCHAR(16) NULL

ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] ALTER COLUMN NO_FEE_TYPE VARCHAR(16) NULL
GO

UPDATE [permit].[ORBC_NO_FEE_TYPE]
SET NO_FEE_TYPE = 'OTHER_USA_GOVT'
WHERE NO_FEE_TYPE = 'ANY_USA_GOVT'

UPDATE [permit].[ORBC_NO_FEE_TYPE]
SET NO_FEE_TYPE = 'USA_FEDERAL_GOVT'
WHERE NO_FEE_TYPE = 'USA_GOVT'

UPDATE [permit].[ORBC_NO_FEE_TYPE]
SET NO_FEE_TYPE = 'MUNICIPALITY'
WHERE NO_FEE_TYPE = 'MUNICPALITY'

ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] ADD CONSTRAINT PK_ORBC_NO_FEE_TYPE PRIMARY KEY CLUSTERED ([NO_FEE_TYPE]);

ALTER TABLE [permit].[ORBC_SPECIAL_AUTH]
   WITH CHECK ADD CONSTRAINT [FK_ORBC_SPECIAL_AUTH_NO_FEE_TYPE] FOREIGN KEY ([NO_FEE_TYPE]) REFERENCES [permit].[ORBC_NO_FEE_TYPE]([NO_FEE_TYPE])

ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] CHECK CONSTRAINT [FK_ORBC_SPECIAL_AUTH_NO_FEE_TYPE]

GO

IF @@ERROR <> 0
   SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)

SET @VersionDescription = 'Updating no fee type column length.'

INSERT [dbo].[ORBC_SYS_VERSION] (
   [VERSION_ID],
   [DESCRIPTION],
   [UPDATE_SCRIPT],
   [REVERT_SCRIPT],
   [RELEASE_DATE]
   )
VALUES (
   40,
   @VersionDescription,
   '$(UPDATE_SCRIPT)',
   '$(REVERT_SCRIPT)',
   getutcdate()
   )

IF @@ERROR <> 0
   SET NOEXEC ON
GO

COMMIT TRANSACTION
GO

IF @@ERROR <> 0
   SET NOEXEC ON
GO

DECLARE @Success AS BIT

SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1)
   PRINT 'The database update succeeded'
ELSE
BEGIN
   IF @@TRANCOUNT > 0
      ROLLBACK TRANSACTION

   PRINT 'The database update failed'
END
GO

