SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

CREATE TABLE [permit].[ORBC_GL_TYPE](	
	[GL_TYPE] [char] (6) NOT NULL,
	[NAME] [varchar] (20) NOT NULL,
	[DESCRIPTION] [varchar] (50) NULL,
	[APP_CREATE_TIMESTAMP] [datetime2](7) DEFAULT (getutcdate()),
	[APP_CREATE_USERID] [nvarchar](30) DEFAULT (user_name()),
	[APP_CREATE_USER_GUID] [char](32) NULL,
	[APP_CREATE_USER_DIRECTORY] [nvarchar](30) DEFAULT (user_name()),
	[APP_LAST_UPDATE_TIMESTAMP] [datetime2](7) DEFAULT (getutcdate()),
	[APP_LAST_UPDATE_USERID] [nvarchar](30) DEFAULT (user_name()),
	[APP_LAST_UPDATE_USER_GUID] [char](32) NULL,
	[APP_LAST_UPDATE_USER_DIRECTORY] [nvarchar](30) DEFAULT (user_name()),
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NULL,
 CONSTRAINT [ORBC_GL_TYPE_PK] PRIMARY KEY CLUSTERED 
(
	[GL_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [permit].[ORBC_GL_CODE_TYPE](	
	[GL_CODE_TYPE] [int] IDENTITY(1,1) NOT NULL,
	[GL_TYPE] [char] (6) NULL,
   [PERMIT_TYPE] [varchar](10) NULL,
	[PAYMENT_METHOD_TYPE] [varchar] (15) NULL,
	[PAYMENT_CARD_TYPE] [varchar] (5) NULL,
	[CLIENT] [char] (3) NOT NULL,
	[RESPONSIBILITY] [char] (5) NOT NULL,
	[SERVICE_LINE] [char] (5) NOT NULL,
	[STOB] [char] (4) NOT NULL,
	[PROJECT] [char] (7) NOT NULL,
	[LOCATION] [char] (6) NOT NULL,
	[FUTURE] [char] (4) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NULL,
 CONSTRAINT [ORBC_GL_CODE_TYPE_PK] PRIMARY KEY CLUSTERED 
(
	[GL_CODE_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE]  WITH CHECK ADD CONSTRAINT [FK_ORBC_GL_CODE_TYPE_GL_TYPE] FOREIGN KEY([GL_TYPE]) REFERENCES [permit].[ORBC_GL_TYPE] ([GL_TYPE])
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE] CHECK CONSTRAINT [FK_ORBC_GL_CODE_TYPE_GL_TYPE]
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PERMIT_TYPE] FOREIGN KEY([PERMIT_TYPE])
REFERENCES [permit].[ORBC_PERMIT_TYPE] ([PERMIT_TYPE])
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE] CHECK CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PERMIT_TYPE]
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE]  WITH CHECK ADD CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PAYMENT_METHOD_TYPE] FOREIGN KEY([PAYMENT_METHOD_TYPE]) REFERENCES [permit].[ORBC_PAYMENT_METHOD_TYPE] ([PAYMENT_METHOD_TYPE])
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE] CHECK CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PAYMENT_METHOD_TYPE]
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE]  WITH CHECK ADD CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PAYMENT_CARD_TYPE] FOREIGN KEY([PAYMENT_CARD_TYPE]) REFERENCES [permit].[ORBC_PAYMENT_CARD_TYPE] ([PAYMENT_CARD_TYPE])
GO
ALTER TABLE [permit].[ORBC_GL_CODE_TYPE] CHECK CONSTRAINT [FK_ORBC_GL_CODE_TYPE_PAYMENT_CARD_TYPE]
GO
INSERT [permit].[ORBC_GL_TYPE] ([GL_TYPE], [NAME], [DESCRIPTION], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'Revenue GL', NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
INSERT [permit].[ORBC_GL_TYPE] ([GL_TYPE], [NAME], [DESCRIPTION], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'Balancing GL', NULL, N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
INSERT [permit].[ORBC_CFS_FILE_STATUS_TYPE] ([CFS_FILE_STATUS_TYPE], [NAME], [DESCRIPTION], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'PROCESSING', N'Processing', N'Creating and sending file to sftp.', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL] ADD  [REPROCESS_FLAG] [char](1) NULL
GO
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] ADD  [REPROCESS_FLAG] [char](1) NULL
GO
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL] WITH CHECK ADD  CONSTRAINT DK_ORBC_CFS_TRANSACTION_DETAIL_REPROCESS_FLAG_VAL CHECK ([REPROCESS_FLAG] IN ('Y','N'));
GO
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL] CHECK CONSTRAINT DK_ORBC_CFS_TRANSACTION_DETAIL_REPROCESS_FLAG_VAL
GO
ALTER TABLE [permit].[ORBC_CFS_TRANSACTION_DETAIL] ADD CONSTRAINT [DK_ORBC_CFS_TRANSACTION_DETAIL_REPROCESS_FLAG] DEFAULT('N') FOR [REPROCESS_FLAG]
GO
INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'MC', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'MD', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'VI', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'PV', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'AM', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'WEB', N'DB', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'MC', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'MD', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'VI', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'PV', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'AM', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'ICEPAY', N'DB', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'POS', null, N'034', N'55730', N'10425', N'4351', N'5573022', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'CASH', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'CHEQUE', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOS', N'GA', null, N'034', N'55730', N'10425', N'4351', N'5573024', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'MC', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'MD', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'VI', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'PV', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'AM', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'WEB', N'DB', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'MC', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'MD', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'VI', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'PV', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'AM', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'ICEPAY', N'DB', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'POS', null, N'034', N'55730', N'10425', N'4351', N'5573022', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'CASH', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'CHEQUE', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROS', N'GA', null, N'034', N'55730', N'10425', N'4351', N'5573024', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'MC', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'MD', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'VI', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'PV', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'AM', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'WEB', N'DB', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'MC', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'MD', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'VI', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'PV', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'AM', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'ICEPAY', N'DB', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'POS', null, N'034', N'55730', N'10425', N'4351', N'5573022', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'CASH', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'CHEQUE', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'TROW', N'GA', null, N'034', N'55730', N'10425', N'4351', N'5573024', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'MC', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'MD', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'VI', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'PV', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'AM', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'WEB', N'DB', N'034', N'55730', N'10425', N'4351', N'5573020', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'MC', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'MD', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'VI', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'PV', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'AM', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'ICEPAY', N'DB', N'034', N'55730', N'10425', N'4351', N'5573021', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'POS', null, N'034', N'55730', N'10425', N'4351', N'5573022', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'CASH', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'CHEQUE', null, N'034', N'55730', N'10425', N'4351', N'5573023', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'R_GL', N'STOW', N'GA', null, N'034', N'55730', N'10425', N'4351', N'5573024', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'GA', null, N'034', N'55730', N'10435', N'1501', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'MC', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'MD', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'VI', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'PV', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'AM', N'034', N'00000', N'10435', N'1522', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOS', N'ICEPAY', N'DB', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'GA', null, N'034', N'55730', N'10435', N'1501', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'MC', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'MD', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'VI', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'PV', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'AM', N'034', N'00000', N'10435', N'1522', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'ICEPAY', N'DB', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROS', N'GA', null, N'034', N'55730', N'10435', N'1501', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'MC', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'MD', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'VI', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'PV', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'AM', N'034', N'00000', N'10435', N'1522', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'TROW', N'ICEPAY', N'DB', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'MC', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'MD', N'034', N'00000', N'10435', N'1490', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'VI', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'PV', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'AM', N'034', N'00000', N'10435', N'1522', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO 
 INSERT [permit].[ORBC_GL_CODE_TYPE] ([GL_TYPE], [PERMIT_TYPE], [PAYMENT_METHOD_TYPE], [PAYMENT_CARD_TYPE], [CLIENT], [RESPONSIBILITY], [SERVICE_LINE], [STOB], [PROJECT], [LOCATION], [FUTURE], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'BAL_GL', N'STOW', N'ICEPAY', N'DB', N'034', N'00000', N'10435', N'1491', N'5500000', N'000000', N'0000', N'dbo', GETUTCDATE(), N'dbo', GETUTCDATE())
GO
ALTER TRIGGER [permit].[ORBC_CFSTRDT_A_S_IUD_TR] ON [permit].[ORBC_CFS_TRANSACTION_DETAIL] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] set END_DATE_HIST = @curr_date where ID in (select ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into [permit].[ORBC_CFS_TRANSACTION_DETAIL_HIST] ([ID], [TRANSACTION_ID], [FILE_NAME], [CFS_FILE_STATUS_TYPE], [ERROR_MESSAGE], [PROCESSSING_DATE_TIME], [REPROCESS_FLAG], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], _CFS_TRANSACTION_DETAIL_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [ID], [TRANSACTION_ID], [FILE_NAME], [CFS_FILE_STATUS_TYPE], [ERROR_MESSAGE], [PROCESSSING_DATE_TIME], [REPROCESS_FLAG], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], (next value for [permit].[ORBC_CFS_TRANSACTION_DETAIL_H_ID_SEQ]) as [_CFS_TRANSACTION_DETAIL_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC orbc_error_handling
END CATCH;
go

IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'DB changes for CGI File and GL Code'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (46, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO

