SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

INSERT [permit].[ORBC_PERMIT_TYPE] ([PERMIT_TYPE], [NAME], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'QRFR', N'Non-Resident Quarterly ICBC Basic Insurance (FR)', NULL, N'dbo', CAST(N'2024-11-06T21:30:33.6366667' AS DateTime2), N'dbo', CAST(N'2024-11-06TT21:30:33.6366667' AS DateTime2))
INSERT [permit].[ORBC_PERMIT_TYPE] ([PERMIT_TYPE], [NAME], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (N'STFR', N'Non-Resident Single Trip ICBC Basic Insurance (FR)', NULL, N'dbo', CAST(N'2024-11-06T21:30:33.6366667' AS DateTime2), N'dbo', CAST(N'2024-11-06TT21:30:33.6366667' AS DateTime2))

IF @@ERROR <> 0 SET NOEXEC ON
GO


DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Add QRFR and STFR permit types to ORBC_PERMIT_TYPE table'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (46, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
