SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

CREATE TABLE [dbo].[ORBC_DOCUMENT_TEMPLATE](
	[TEMPLATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_NAME] [varchar](50) NOT NULL,
	[TEMPLATE_VERSION] [int] NOT NULL,
	[DOCUMENT_ID] [varchar](50) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_DOCUMENT_TEMPLATE] PRIMARY KEY CLUSTERED 
(
	[TEMPLATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORBC_DOCUMENT_TEMPLATE]
ADD CONSTRAINT UK_ORBC_DOCUMENT_TEMPLATE UNIQUE (TEMPLATE_NAME, TEMPLATE_VERSION);

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Initial creation of entities for generating a document'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (5, @VersionDescription, '$(FILE_HASH)', getutcdate())

COMMIT