SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

CREATE TABLE [dbo].[ORBC_PDF_TEMPLATE](
	[TEMPLATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_NAME] [varchar](50) NOT NULL,
	[PERMIT_TYPE_ID] [varchar](10) NOT NULL,
	[TEMPLATE_VERSION] [int] NOT NULL,
	[DMS_REF_ID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ORBC_PDF_TEMPLATE] PRIMARY KEY CLUSTERED 
(
	[TEMPLATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/* Add Foreign Key constraint for associating Template Name with Permit Type (Example 'TROS') */
ALTER TABLE [dbo].[ORBC_PDF_TEMPLATE]
ADD CONSTRAINT FK_PERMIT_TYPE_ID
FOREIGN KEY (PERMIT_TYPE_ID) REFERENCES [permit].[ORBC_VT_PERMIT_TYPE](PERMIT_TYPE_ID);

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Initial creation of entities for generating a pdf'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (5, @VersionDescription, '$(FILE_HASH)', getdate())

COMMIT