SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [permit].[ORBC_PAYMENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MERCHANT_ID] [int] NOT NULL,
	[ORDER_NUMBER] [varchar](20) NOT NULL,
	[PAYMENT_AMOUNT] [decimal] (19, 4) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_PAYMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [permit].[ORBC_TRANSACTION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRANSACTION_NUMBER] [varchar](20) NOT NULL,
	[TRANSACTION_APPROVED] [bit] NOT NULL,
	[TRANSACTION_AUTH_CODE] [varchar] (10) NOT NULL,
	[TRANSACTION_CARD_TYPE] [nvarchar](5) NOT NULL,
	[TRANSACTION_CVD_ID] [int] NOT NULL,
	[TRANSACTION_PAYMENT_METHOD] [nvarchar](5) NOT NULL,
	[TRANSACTION_RESPONSE_TYPE] [varchar] (10) NOT NULL,
	[TRANSACTION_DATE] [datetime2](7) NULL,
	[TRANSACTION_LANGUAGE] [varchar] (10) NOT NULL,
	[TRANSACTION_TYPE] [varchar] (5) NOT NULL,
	[TRANSACTION_MESSAGE_ID] [bigint] NOT NULL,
	[TRANSACTION_MESSAGE_TEXT] [varchar](100) NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_TRANSACTION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [permit].[ORBC_PAYMENT_TRANSACTIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PAYMENT_ID] [bigint] NOT NULL,
	[TRANSACTION_ID] [bigint] NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_PAYMENT_TRANSACTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [permit].[ORBC_PAYMENT_PERMITS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PAYMENT_ID] [bigint] NOT NULL,
	[PERMIT_ID] [bigint] NOT NULL,
	[CONCURRENCY_CONTROL_NUMBER] [int] NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ORBC_PAYMENT_PERMITS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [permit].[ORBC_PAYMENT_TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_PAYMENT_TRANSACTION_PAYMENT_ID] FOREIGN KEY([PAYMENT_ID])
REFERENCES [permit].[ORBC_PAYMENT] ([ID])
GO

ALTER TABLE [permit].[ORBC_PAYMENT_TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_PAYMENT_TRANSACTION_TRANSACTION_ID] FOREIGN KEY([TRANSACTION_ID])
REFERENCES [permit].[ORBC_TRANSACTION] ([ID])
GO

ALTER TABLE [permit].[ORBC_PAYMENT_PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_PAYMENT_PERMITS_PAYMENT_ID] FOREIGN KEY([PAYMENT_ID])
REFERENCES [permit].[ORBC_PAYMENT] ([ID])
GO

ALTER TABLE [permit].[ORBC_PAYMENT_PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_ORBC_PAYMENT_PERMITS_PERMIT_ID] FOREIGN KEY([PERMIT_ID])
REFERENCES [permit].[ORBC_PERMIT] ([ID])
GO


DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Initial creation of entities for Permit Payment'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (7, @VersionDescription, '$(FILE_HASH)', getdate())


COMMIT
