SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
CREATE FULLTEXT CATALOG PermitDataFTCat AS DEFAULT
GO
CREATE FULLTEXT INDEX ON [permit].[ORBC_PERMIT_DATA](PERMIT_DATA) KEY INDEX PK_ORBC_PERMIT_DATA;
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Creation of full text search index on ORBC_PERMIT_DATA table.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [UPDATE_SCRIPT], [REVERT_SCRIPT], [RELEASE_DATE]) VALUES (8, @VersionDescription, '$(UPDATE_SCRIPT)', '$(REVERT_SCRIPT)', getutcdate())
