import { PermitType } from '../enum/permit-type.enum';

export const QUARTERLY_PERMIT_TYPES: PermitType[] = [
  PermitType.QUARTERLY_NON_REG_INS_BUS,
  PermitType.NON_RESIDENT_QUARTERLY_CONDITIONAL_LICENSE,
  PermitType.QUARTERLY_NON_RESIDENT_REG_INS_COMM_VEHICLE,
  PermitType.NON_RESIDENT_QUARTERLY_FARM_TRACTOR,
  PermitType.QUARTERLY_NON_RESIDENT_REG_INS_FARM_VEHICLE,
  PermitType.NON_RESIDENT_QUARTERLY_X_PLATED,
  PermitType.NON_RESIDENT_QUARTERLY_ICBC_BASIC_INSURANCE_FR,
];
export const PERMIT_TYPES_FOR_QUEUE: readonly PermitType[] = [
  PermitType.SINGLE_TRIP_OVERSIZE,
];

export const STOS_MAX_ALLOWED_DURATION_AMEND = 30;
