SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

DELETE FROM [access].[ORBC_GROUP_ROLE] WHERE USER_AUTH_GROUP_TYPE IN ('HQADMIN', 'FINANCE')
GO
UPDATE [dbo].[ORBC_IDIR_USER]
SET USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
WHERE USER_AUTH_GROUP_TYPE IN ('HQADMIN', 'FINANCE')
GO
UPDATE [dbo].[ORBC_PENDING_IDIR_USER]
SET USER_AUTH_GROUP_TYPE = 'IDIRBASIC'
WHERE USER_AUTH_GROUP_TYPE IN ('HQADMIN', 'FINANCE')
GO
DELETE FROM [access].[ORBC_ROLE_TYPE] WHERE ROLE_TYPE IN (
  'ORBC-READ-SPECIAL-AUTH',
  'ORBC-READ-NOFEE',
  'ORBC-WRITE-NOFEE',
  'ORBC-READ-LCV-FLAG',
  'ORBC-WRITE-LCV-FLAG',
  'ORBC-READ-LOA',
  'ORBC-WRITE-LOA'
)
GO
DELETE FROM [access].[ORBC_USER_AUTH_GROUP_TYPE] WHERE USER_AUTH_GROUP_TYPE IN ('HQADMIN', 'FINANCE')
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Removing auth groups HQADMIN and FINANCE'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (12, @VersionDescription, getutcdate())
