SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

UPDATE [dops].[ORBC_DOCUMENT_TEMPLATE] SET TEMPLATE_NAME='PERMIT_TROS',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE TEMPLATE_NAME='PERMIT'

IF @@ERROR <> 0 SET NOEXEC ON
GO
UPDATE [dops].[ORBC_DOCUMENT_TEMPLATE] SET TEMPLATE_NAME='PERMIT_TROS_VOID',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE TEMPLATE_NAME='PERMIT_VOID'

IF @@ERROR <> 0 SET NOEXEC ON
GO
UPDATE [dops].[ORBC_DOCUMENT_TEMPLATE] SET TEMPLATE_NAME='PERMIT_TROS_REVOKED',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE TEMPLATE_NAME='PERMIT_REVOKED'

IF @@ERROR <> 0 SET NOEXEC ON
GO
UPDATE [dops].[ORBC_DOCUMENT] SET FILE_NAME='tros-template-v1.docx',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE ID IN (SELECT DOCUMENT_ID FROM [dops].[ORBC_DOCUMENT_TEMPLATE] WHERE TEMPLATE_NAME='PERMIT_TROS')

IF @@ERROR <> 0 SET NOEXEC ON
GO
UPDATE [dops].[ORBC_DOCUMENT] SET FILE_NAME='tros-template-void-template-v1.docx',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE ID IN (SELECT DOCUMENT_ID FROM [dops].[ORBC_DOCUMENT_TEMPLATE] WHERE TEMPLATE_NAME='PERMIT_TROS_VOID')

IF @@ERROR <> 0 SET NOEXEC ON
GO
UPDATE [dops].[ORBC_DOCUMENT] SET FILE_NAME='tros-template-revoked-template-v1.docx',DB_LAST_UPDATE_TIMESTAMP=GETUTCDATE() WHERE ID IN (SELECT DOCUMENT_ID FROM [dops].[ORBC_DOCUMENT_TEMPLATE] WHERE TEMPLATE_NAME='PERMIT_TROS_REVOKED')

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Revert the name of permit template documents'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (23, @VersionDescription, getutcdate())
IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO

