SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO


IF @@ERROR <> 0 SET NOEXEC ON
GO
DELETE FROM [cgi].[ORBC_CGI_BATCH_HEADER] WHERE ROLE_TYPE IN ('ORBC-SEND-NOTIFICATION')


IF @@ERROR <> 0 SET NOEXEC ON
GO
DELETE FROM [cgi].[ORBC_CGI_JOURNAL_HEADER] WHERE ROLE_TYPE IN ('ORBC-SEND-NOTIFICATION')


IF @@ERROR <> 0 SET NOEXEC ON
GO
DELETE FROM [cgi].[ORBC_CGI_JOURNAL_VOUCHER] WHERE ROLE_TYPE IN ('ORBC-SEND-NOTIFICATION')

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database update failed'
END
GO
