SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    DROP TABLE [permit].[ORBC_CREDIT_ACCOUNT]
    DROP TABLE [permit].[ORBC_CREDIT_ACCOUNT_TYPE]
    DROP TABLE [permit].[ORBC_CREDIT_ACCOUNT_STATUS_TYPE]    
    DROP SEQUENCE [permit].[ORBC_CREDIT_ACCOUNT_NUMBER_SEQ]
  COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting initial creation of entities for Credit Accounts.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (27, @VersionDescription, getutcdate())
