SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
  IF @@ERROR <> 0 SET NOEXEC ON
  GO
  DELETE FROM [dbo].[ORBC_DIRECTORY_TYPE] WHERE DIRECTORY_TYPE = 'SERVICE_ACCOUNT'
  GO

  IF @@ERROR <> 0 SET NOEXEC ON
  GO
  ALTER TABLE [permit].[ORBC_TRANSACTION] DROP COLUMN [PAYER_NAME]
  GO

  IF @@ERROR <> 0 SET NOEXEC ON
  GO
ALTER TABLE [permit].[ORBC_TRANSACTION_HIST]  DROP COLUMN [PAYER_NAME]
  GO
  COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting initial creation ofservice account in directory table.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (29, @VersionDescription, getutcdate())
