SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] DROP CONSTRAINT [DF_ORBC_SPECIAL_AUTH_DB_CREATE_USERID]
    ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] DROP CONSTRAINT [DF_ORBC_SPECIAL_AUTH_DB_CREATE_TIMESTAMP]
    ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] DROP CONSTRAINT [DF_ORBC_SPECIAL_AUTH_DB_LAST_UPDATE_USERID]
    ALTER TABLE [permit].[ORBC_SPECIAL_AUTH] DROP CONSTRAINT [DF_ORBC_SPECIAL_AUTH_DB_LAST_UPDATE_TIMESTAMP]
    ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] DROP CONSTRAINT [DF_ORBC_NO_FEE_TYPE_DB_CREATE_USERID]
    ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] DROP CONSTRAINT [DF_ORBC_NO_FEE_TYPE_DB_CREATE_TIMESTAMP]
    ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] DROP CONSTRAINT [DF_ORBC_NO_FEE_TYPE_DB_LAST_UPDATE_USERID]
    ALTER TABLE [permit].[ORBC_NO_FEE_TYPE] DROP CONSTRAINT [DF_ORBC_NO_FEE_TYPE_DB_LAST_UPDATE_TIMESTAMP] 
    -- History table should not have any constraints 
    -- ALTER TABLE [permit].[ORBC_SPECIAL_AUTH_HIST] ALTER COLUMN NO_FEE_TYPE VARCHAR(12) NOT NULL
    COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Deleting constraint from DB related coulmns form special authorization and no fee tables'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (38, @VersionDescription, getutcdate())
