SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    DROP TABLE [case].[ORBC_CASE_DOCUMENT]    
    DROP TABLE [case].[ORBC_CASE_ACTIVITY]
    DROP TABLE [case].[ORBC_CASE_NOTES]
    DROP TABLE [case].[ORBC_CASE_ACTIVITY_TYPE]
    DROP TABLE [case].[ORBC_CASE_EVENT]
    DROP TABLE [case].[ORBC_CASE_EVENT_TYPE]
    DROP TABLE [case].[ORBC_CASE]
    DROP TABLE [case].[ORBC_CASE_TYPE]
    DROP TABLE [case].[ORBC_CASE_STATUS_TYPE]
    DROP SCHEMA [case]
    COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Revert Case/Queue management and related Db objects'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (39, @VersionDescription, getutcdate())
