SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP CONSTRAINT FK_ORBC_LOA_DETAILS_PREVIOUS_LOA_ID
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP CONSTRAINT FK_ORBC_LOA_DETAILS_ORIGINAL_LOA_ID
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP COLUMN PREVIOUS_LOA_ID
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP COLUMN ORIGINAL_LOA_ID
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] ALTER COLUMN [START_DATE] [varchar](10) NOT NULL
      ALTER TABLE [permit].[ORBC_LOA_DETAILS] ALTER COLUMN [EXPIRY_DATE] [varchar](10) NULL
  COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting creation of entities for LoA.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (40, @VersionDescription, getutcdate())

