SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP CONSTRAINT [DF_ORBC_LOA_DETAILS_REVISION]
    ALTER TABLE [permit].[ORBC_LOA_DETAILS] DROP COLUMN REVISION
    COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Deleting constraint and dropping revision column from orbc loa details table.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (40, @VersionDescription, getutcdate())
