SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    DROP TABLE [case].[ORBC_CASE_DOCUMENT_HIST]
    DROP TABLE [case].[ORBC_CASE_DOCUMENT]
    DROP SEQUENCE [case].[ORBC_CASE_DOCUMENT_H_ID_SEQ]
    DROP TABLE [case].[ORBC_CASE_ACTIVITY_HIST]
    DROP TABLE [case].[ORBC_CASE_ACTIVITY]
    DROP SEQUENCE [case].[ORBC_CASE_ACTIVITY_H_ID_SEQ]
    DROP TABLE [case].[ORBC_CASE_NOTES_HIST]
    DROP TABLE [case].[ORBC_CASE_NOTES]
    DROP SEQUENCE [case].[ORBC_CASE_NOTES_H_ID_SEQ]
    DROP TABLE [case].[ORBC_CASE_ACTIVITY_TYPE]
    DROP TABLE [case].[ORBC_CASE_EVENT_HIST]
    DROP TABLE [case].[ORBC_CASE_EVENT]
    DROP SEQUENCE [case].[ORBC_CASE_EVENT_H_ID_SEQ]
    DROP TABLE [case].[ORBC_CASE_EVENT_TYPE]
    DROP TABLE [case].[ORBC_CASE_HIST]
    DROP TABLE [case].[ORBC_CASE]
    DROP SEQUENCE [case].[ORBC_CASE_H_ID_SEQ]
    DROP TABLE [case].[ORBC_CASE_TYPE]
    DROP TABLE [case].[ORBC_CASE_STATUS_TYPE]
    DROP SCHEMA [case]
    DELETE FROM [permit].[ORBC_PERMIT_STATUS_TYPE] WHERE [PERMIT_STATUS_TYPE] ='IN_QUEUE'
    COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Revert Case/Queue management and related Db objects'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (41, @VersionDescription, getutcdate())
