SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
   BEGIN TRANSACTION
   DROP TABLE [permit].[ORBC_PERMIT_LOA_HIST]
   ALTER TABLE [permit].[ORBC_PERMIT_LOA] DROP CONSTRAINT [FK_ORBC_PERMIT_LOA_LOA_ID]
   ALTER TABLE [permit].[ORBC_PERMIT_LOA] DROP CONSTRAINT [FK_ORBC_PERMIT_LOA_PERMIT_ID]
   ALTER TABLE [permit].[ORBC_PERMIT_LOA] DROP CONSTRAINT [CK_ORBC_PERMIT_LOA_UNQ]
   DROP TABLE [permit].[ORBC_PERMIT_LOA]
   DROP SEQUENCE [permit].[ORBC_PERMIT_LOA_H_ID_SEQ]
END TRY

BEGIN CATCH
   IF @@TRANCOUNT > 0
      ROLLBACK;

   THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)

SET @VersionDescription = 'Revert permit LoA association related Db objects'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID],[DESCRIPTION],[RELEASE_DATE]) VALUES (44,@VersionDescription,getutcdate())
