SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
GO

DROP TABLE [permit].[ORBC_GL_CODE_TYPE]
GO
DROP TABLE [permit].[ORBC_GL_TYPE]
GO
COMMIT

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting addition of GL Type and GL Code Type tables'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (45, @VersionDescription, getutcdate())
