SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON

BEGIN TRY
  BEGIN TRANSACTION
    DROP TABLE [permit].[ORBC_PERMIT_COMMENTS]
    DROP TABLE [permit].[ORBC_PERMIT_STATE]
    DROP TABLE [permit].[ORBC_PERMIT_DATA]
    DROP TABLE [permit].[ORBC_PERMIT]
    DROP TABLE [permit].[ORBC_PERMIT_APPLICATION_ORIGIN_TYPE]
    DROP TABLE [permit].[ORBC_PERMIT_APPROVAL_SOURCE_TYPE]
    DROP TABLE [permit].[ORBC_PERMIT_ISSUED_BY_TYPE]
    DROP TABLE [permit].[ORBC_PERMIT_TYPE]
    DROP TABLE [permit].[ORBC_PERMIT_STATUS_TYPE]
    DROP SEQUENCE [permit].[ORBC_PERMIT_NUMBER_SEQ]
    DROP SCHEMA [permit]
  COMMIT
END TRY

BEGIN CATCH
  IF @@TRANCOUNT > 0 
    ROLLBACK;
  THROW
END CATCH

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting initial creation of entities for applying for and issuing permits'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (3, @VersionDescription, getutcdate())
