SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

-- Foreign key indexes on all tables
DROP INDEX [tps].[ETL_PROCESSES].[IX_FK_ETL_PROCESSES_ETL_PROCESS_TYPE];
DROP INDEX [dbo].[ORBC_ADDRESS].[IX_FK_ORBC_ADDRESS_PROVINCE];
DROP INDEX [case].[ORBC_CASE_ACTIVITY].[IX_FK_ORBC_CASE_ACTIVITY_CASE_ACTIVITY_TYPE];
DROP INDEX [case].[ORBC_CASE_ACTIVITY].[IX_FK_ORBC_CASE_ACTIVITY_CASE_EVENT_ID];
DROP INDEX [case].[ORBC_CASE_ACTIVITY].[IX_FK_ORBC_CASE_ACTIVITY_CASE_ID];
DROP INDEX [case].[ORBC_CASE].[IX_FK_ORBC_CASE_CASE_STATUS_TYPE];
DROP INDEX [case].[ORBC_CASE].[IX_FK_ORBC_CASE_CASE_TYPE];
DROP INDEX [case].[ORBC_CASE_DOCUMENT].[IX_FK_ORBC_CASE_DOCUMENT_CASE_EVENT_ID];
DROP INDEX [case].[ORBC_CASE_DOCUMENT].[IX_FK_ORBC_CASE_DOCUMENT_CASE_ID];
DROP INDEX [case].[ORBC_CASE_EVENT].[IX_FK_ORBC_CASE_EVENT_CASE_EVENT_TYPE];
DROP INDEX [case].[ORBC_CASE_NOTES].[IX_FK_ORBC_CASE_NOTES_CASE_EVENT_ID];
DROP INDEX [case].[ORBC_CASE_NOTES].[IX_FK_ORBC_CASE_NOTES_CASE_ID];
DROP INDEX [case].[ORBC_CASE].[IX_FK_ORBC_CASE_ORIGINAL_CASE_ID];
DROP INDEX [case].[ORBC_CASE].[IX_FK_ORBC_CASE_PERMIT_ID];
DROP INDEX [case].[ORBC_CASE].[IX_FK_ORBC_CASE_PREVIOUS_CASE_ID];
DROP INDEX [dbo].[ORBC_COMPANY].[IX_FK_ORBC_COMPANY_DIRECTORY];
DROP INDEX [dbo].[ORBC_COMPANY].[IX_FK_ORBC_COMPANY_MAILING_ADDRESS];
DROP INDEX [dbo].[ORBC_COMPANY].[IX_FK_ORBC_COMPANY_PRIMARY_CONTACT];
DROP INDEX [dbo].[ORBC_COMPANY_SUSPEND_ACTIVITY].[IX_FK_ORBC_COMPANY_SUSPEND_ACTIVITY_ORBC_COMPANY];
DROP INDEX [dbo].[ORBC_COMPANY_SUSPEND_ACTIVITY].[IX_FK_ORBC_COMPANY_SUSPEND_ACTIVITY_SUSPEND_ACTIVITY_TYPE];
DROP INDEX [dbo].[ORBC_COMPANY_USER].[IX_FK_ORBC_COMPANY_USER_COMPANY];
DROP INDEX [dbo].[ORBC_COMPANY_USER].[IX_FK_ORBC_COMPANY_USER_USER];
DROP INDEX [dbo].[ORBC_COMPANY_USER].[IX_FK_ORBC_COMPANY_USER_USER_AUTH_GROUP];
DROP INDEX [dbo].[ORBC_COMPANY_USER].[IX_FK_ORBC_COMPANY_USER_USER_STATUS];
DROP INDEX [dbo].[ORBC_CONTACT].[IX_FK_ORBC_CONTACT_PROVINCE];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY].[IX_FK_ORBC_CREDIT_ACCOUNT_ACTIVITY_CREDIT_ACCOUNT_ACTIVITY_TYPE];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY].[IX_FK_ORBC_CREDIT_ACCOUNT_ACTIVITY_CREDIT_ACCOUNT_ID];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT].[IX_FK_ORBC_CREDIT_ACCOUNT_COMPANY_ID];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT].[IX_FK_ORBC_CREDIT_ACCOUNT_CREDIT_ACCOUNT_STATUS_TYPE];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT].[IX_FK_ORBC_CREDIT_ACCOUNT_CREDIT_ACCOUNT_TYPE];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT_USER].[IX_FK_ORBC_CREDIT_ACCOUNT_USER_COMPANY_ID];
DROP INDEX [permit].[ORBC_CREDIT_ACCOUNT_USER].[IX_FK_ORBC_CREDIT_ACCOUNT_USER_CREDIT_ACCOUNT_ID];
DROP INDEX [permit].[ORBC_GL_CODE_TYPE].[IX_FK_ORBC_GL_CODE_TYPE_GL_TYPE];
DROP INDEX [permit].[ORBC_GL_CODE_TYPE].[IX_FK_ORBC_GL_CODE_TYPE_PAYMENT_CARD_TYPE];
DROP INDEX [permit].[ORBC_GL_CODE_TYPE].[IX_FK_ORBC_GL_CODE_TYPE_PAYMENT_METHOD_TYPE];
DROP INDEX [permit].[ORBC_GL_CODE_TYPE].[IX_FK_ORBC_GL_CODE_TYPE_PERMIT_TYPE];
DROP INDEX [access].[ORBC_GROUP_ROLE].[IX_FK_ORBC_GROUP_ROLE_ROLE];
DROP INDEX [access].[ORBC_GROUP_ROLE].[IX_FK_ORBC_GROUP_ROLE_USER_AUTH_GROUP];
DROP INDEX [permit].[ORBC_LOA_DETAILS].[IX_FK_ORBC_LOA_DETAILS_COMPANY];
DROP INDEX [permit].[ORBC_LOA_DETAILS].[IX_FK_ORBC_LOA_DETAILS_ORIGINAL_LOA_ID];
DROP INDEX [permit].[ORBC_LOA_DETAILS].[IX_FK_ORBC_LOA_DETAILS_PREVIOUS_LOA_ID];
DROP INDEX [permit].[ORBC_LOA_PERMIT_TYPE_DETAILS].[IX_FK_ORBC_LOA_PERMIT_TYPE_LOA_ID];
DROP INDEX [permit].[ORBC_LOA_PERMIT_TYPE_DETAILS].[IX_FK_ORBC_LOA_PERMIT_TYPES_PERMIT_TYPE];
DROP INDEX [permit].[ORBC_LOA_VEHICLES].[IX_FK_ORBC_LOA_VEHICLES_LOA_ID];
DROP INDEX [dbo].[ORBC_PENDING_IDIR_USER].[IX_FK_ORBC_PENDING_IDIR_USER_AUTH_GROUP];
DROP INDEX [dbo].[ORBC_PENDING_USER].[IX_FK_ORBC_PENDING_USER_AUTH_GROUP];
DROP INDEX [dbo].[ORBC_PENDING_USER].[IX_FK_ORBC_PENDING_USER_COMPANY];
DROP INDEX [permit].[ORBC_PERMIT_COMMENTS].[IX_FK_ORBC_PERMIT_COMMENTS_PERMIT];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_FK_ORBC_PERMIT_ID];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PARENT_PERMIT];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PERMIT_APPLICATION_ORIGIN];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PERMIT_APPROVAL_SOURCE];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PERMIT_ISSUED_BY];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PERMIT_STATUS_TYPE];
DROP INDEX [permit].[ORBC_PERMIT].[IX_FK_ORBC_PERMIT_PERMIT_TYPE];
DROP INDEX [permit].[ORBC_PERMIT_STATE].[IX_FK_ORBC_PERMIT_STATE_PERMIT];
DROP INDEX [permit].[ORBC_PERMIT_STATE].[IX_FK_ORBC_PERMIT_STATE_PERMIT_STATUS];
DROP INDEX [dbo].[ORBC_POWER_UNIT].[IX_FK_ORBC_POWER_UNIT_COMPANY];
DROP INDEX [dbo].[ORBC_POWER_UNIT].[IX_FK_ORBC_POWER_UNIT_POWER_UNIT_TYPE];
DROP INDEX [dbo].[ORBC_POWER_UNIT].[IX_FK_ORBC_POWER_UNIT_PROVINCE];
DROP INDEX [permit].[ORBC_SPECIAL_AUTH].[IX_FK_ORBC_SPECIAL_AUTH_COMPANY_ID];
DROP INDEX [permit].[ORBC_SPECIAL_AUTH].[IX_FK_ORBC_SPECIAL_AUTH_NO_FEE_TYPE];
DROP INDEX [dbo].[ORBC_TRAILER].[IX_FK_ORBC_TRAILER_COMPANY];
DROP INDEX [dbo].[ORBC_TRAILER].[IX_FK_ORBC_TRAILER_PROVINCE];
DROP INDEX [dbo].[ORBC_TRAILER].[IX_FK_ORBC_TRAILER_TRAILER_TYPE];
DROP INDEX [dbo].[ORBC_USER].[IX_FK_ORBC_USER_CONTACT];
DROP INDEX [dbo].[ORBC_USER].[IX_FK_ORBC_USER_DIRECTORY];
DROP INDEX [dbo].[ORBC_USER].[IX_FK_ORBC_USER_USER_AUTH_GROUP];
DROP INDEX [dbo].[ORBC_USER].[IX_FK_ORBC_USER_USER_STATUS];
DROP INDEX [permit].[ORBC_CFS_TRANSACTION_DETAIL].[IX_ORBC_CFS_DETAILS_TRANSACTION_ID_FK];
DROP INDEX [permit].[ORBC_CFS_TRANSACTION_DETAIL].[IX_ORBC_CFS_TRANSACTION_DETAIL_FILE_STATUS_FK];
DROP INDEX [dops].[ORBC_DOCUMENT].[IX_ORBC_DOCUMENT_COMPANY_ID_FK];
DROP INDEX [permit].[ORBC_LOA_DETAILS].[IX_ORBC_LOA_DETAILS_DOCUMENT_ID_FK];
DROP INDEX [permit].[ORBC_LOA_VEHICLES].[IX_ORBC_LOA_VEHICLES_POWER_UNIT_ID_FK];
DROP INDEX [permit].[ORBC_LOA_VEHICLES].[IX_ORBC_LOA_VEHICLES_TRAILER_ID_FK];
DROP INDEX [permit].[ORBC_PERMIT_TRANSACTION].[IX_ORBC_PERMIT_TRANSACTION_PERMIT_ID_FK];
DROP INDEX [permit].[ORBC_PERMIT_TRANSACTION].[IX_ORBC_PERMIT_TRANSACTION_TRANSACTION_ID_FK];
DROP INDEX [permit].[ORBC_RECEIPT].[IX_ORBC_RECEIPT_TRANSACTION_ID_FK];
DROP INDEX [permit].[ORBC_TRANSACTION].[IX_ORBC_TRANSACTION_CARD_TYPE_FK];
DROP INDEX [permit].[ORBC_TRANSACTION].[IX_ORBC_TRANSACTION_PAYMENT_METHOD_FK];
DROP INDEX [permit].[ORBC_TRANSACTION].[IX_ORBC_TRANSACTION_TYPE_FK];
GO

-- Targeted indexes for permit search and sort
DROP INDEX [permit].[ORBC_PERMIT].[IX_PERMIT_NUMBER];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_START_DATE];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_EXPIRY_DATE];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_UNIT_NUMBER];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_PLATE];
DROP INDEX [permit].[ORBC_PERMIT_DATA].[IX_VIN];
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting adding indexes on foreign keys and permit sort columns'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (49, @VersionDescription, getutcdate())

IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database revert succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database revert failed'
END
GO