SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

/*Below delete scripts from ORBC_POWER_UNIT_TYPE and ORBC_TRAILER_TYPE have been commented
 due to FK constraints. Execute them manually if needed. */
/*
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='CRANEAT';
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='CRANEMB';
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='FARMTRC';
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='PICKRTR';
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='RBTRLDR';
DELETE FROM dbo.ORBC_POWER_UNIT_TYPE WHERE POWER_UNIT_TYPE='TLSCONV';
DELETE FROM dbo.ORBC_TRAILER_TYPE WHERE TRAILER_TYPE='FECVYPT';
DELETE FROM dbo.ORBC_TRAILER_TYPE WHERE TRAILER_TYPE='FEWHLPR';
DELETE FROM dbo.ORBC_TRAILER_TYPE WHERE TRAILER_TYPE='LOGLGCY';
*/

-- Remove the newly added policy configuration
DELETE FROM [dbo].[ORBC_POLICY_CONFIGURATION]
WHERE POLICY_CONFIGURATION_ID = (SELECT MAX(POLICY_CONFIGURATION_ID) FROM [dbo].[ORBC_POLICY_CONFIGURATION])
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting updates to support new vehicle types for TROS and TROW'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (57, @VersionDescription, getutcdate())
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database revert succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database revert failed'
END
GO