SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

ALTER TABLE permit.ORBC_PERMIT_TYPE
DROP COLUMN GARMS_SERVICE_CODE;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

DROP TABLE [permit].[ORBC_GARMS_FILE_TRANSACTION_HIST]
GO
DROP TABLE [permit].[ORBC_GARMS_FILE_TRANSACTION]
GO
DROP TABLE [permit].[ORBC_GARMS_EXTRACT_FILE_HIST]
GO
DROP TABLE [permit].[ORBC_GARMS_EXTRACT_FILE]
GO
DROP TABLE [permit].[ORBC_GARMS_EXTRACT_TYPE]
GO
DROP SEQUENCE [permit].[ORBC_GARMS_EXTRACT_FILE_H_ID_SEQ]
GO
DROP SEQUENCE [permit].[ORBC_GARMS_FILE_TRANSACTION_H_ID_SEQ]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO


DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting support for new GARMS file upload and processing'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [RELEASE_DATE]) VALUES (64, @VersionDescription, getutcdate())
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

COMMIT TRANSACTION
GO

IF @@ERROR <> 0 SET NOEXEC ON
GO

DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database revert succeeded'
ELSE BEGIN
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   PRINT 'The database revert failed'
END
GO