SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DROP TRIGGER [dbo].[ORBC_LOGIN_I_S_U_TR]
ALTER TABLE [dbo].[ORBC_LOGIN_HIST] DROP CONSTRAINT [ORBC_LOGIN_HIST_UK]
ALTER TABLE [dbo].[ORBC_LOGIN_HIST] DROP CONSTRAINT [ORBC_LOGIN_HIST_PK]
DROP TABLE [dbo].[ORBC_LOGIN_HIST]
DROP SEQUENCE [dbo].[ORBC_LOGIN_H_ID_SEQ]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [DF_ORBC_LOGIN_LOGIN_DATE_TIME]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [ORBC_LOGIN_USER_DIRECTORY_FK]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [ORBC_LOGIN_DB_CREATE_USERID_DEF]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [ORBC_LOGIN_DB_CREATE_TIMESTAMP_DEF]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [ORBC_LOGIN_DB_LAST_UPDATE_USERID_DEF]
ALTER TABLE [dbo].[ORBC_LOGIN] DROP CONSTRAINT [ORBC_LOGIN_LAST_UPDATE_TIMESTAMP_DEF] 
DROP TABLE [dbo].[ORBC_LOGIN]

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)

SET @VersionDescription = 'Drop orbc login table and associated components.'

INSERT [dbo].[ORBC_SYS_VERSION] (
	[VERSION_ID]
	,[DESCRIPTION]
	,[RELEASE_DATE]
	)
VALUES (
	78
	,@VersionDescription
	,getutcdate()
	)
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

COMMIT TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @Success AS BIT

SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1)
	PRINT 'The database revert succeeded'
ELSE
BEGIN
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION

	PRINT 'The database revert failed'
END
GO