SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

ALTER TABLE [permit].ORBC_PERMIT_TRANSACTION DROP CONSTRAINT [ORBC_PERMIT_TRANSACTION_PERMIT_ID_FK]
ALTER TABLE [permit].ORBC_PERMIT_TRANSACTION DROP CONSTRAINT [ORBC_PERMIT_TRANSACTION_TRANSACTION_ID_FK]
ALTER TABLE [permit].ORBC_RECEIPT DROP CONSTRAINT [ORBC_RECEIPT_TRANSACTION_ID_FK]
DROP TABLE [permit].[ORBC_PERMIT_TRANSACTION]
DROP TABLE [permit].[ORBC_TRANSACTION]
DROP TABLE [permit].[ORBC_VT_PAYMENT_METHOD]
DROP TABLE [permit].[ORBC_RECEIPT]


DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting initial creation of entities for Payment.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (6, @VersionDescription, '$(FILE_HASH)', getutcdate())

COMMIT