SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO
DROP INDEX IX_ORBC_PERMIT_COMPUTED_TPS_PERMIT_NUMBER on permit.ORBC_PERMIT;

IF @@ERROR <> 0
	SET NOEXEC ON
GO
ALTER TABLE permit.ORBC_PERMIT DROP COLUMN COMPUTED_TPS_PERMIT_NUMBER;

IF @@ERROR <> 0
	SET NOEXEC ON
GO
DROP INDEX IX_ORBC_PERMIT_COMPUTED_PERMIT_NUMBER on permit.ORBC_PERMIT;

IF @@ERROR <> 0
	SET NOEXEC ON
GO
ALTER TABLE permit.ORBC_PERMIT DROP COLUMN COMPUTED_PERMIT_NUMBER;

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)

SET @VersionDescription = 'Revert computed columns and corresponding indexes on the permit.ORBC_PERMIT table with PERMIT_NUMBER and TPS_PERMIT_NUMBER columns'

INSERT [dbo].[ORBC_SYS_VERSION] (
	[VERSION_ID]
	,[DESCRIPTION]
	,[RELEASE_DATE]
	)
VALUES (
	80
	,@VersionDescription
	,getutcdate()
	)
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

COMMIT TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @Success AS BIT

SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1)
	PRINT 'The database revert succeeded'
ELSE
BEGIN
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION

	PRINT 'The database revert failed'
END
GO