SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

SET XACT_ABORT ON
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

BEGIN TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO
DELETE FROM dops.ORBC_DOCUMENT_TEMPLATE where TEMPLATE_NAME='PERMIT_STOW' AND TEMPLATE_VERSION='1';
DELETE FROM dops.ORBC_DOCUMENT_TEMPLATE where TEMPLATE_NAME='PERMIT_STOW_VOID' AND TEMPLATE_VERSION='1';
DELETE FROM dops.ORBC_DOCUMENT_TEMPLATE where TEMPLATE_NAME='PERMIT_STOW_REVOKED' AND TEMPLATE_VERSION='1';


IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @VersionDescription VARCHAR(255)

SET @VersionDescription = 'Revert STOW permit templates'

INSERT [dbo].[ORBC_SYS_VERSION] (
	[VERSION_ID]
	,[DESCRIPTION]
	,[RELEASE_DATE]
	)
VALUES (
	81
	,@VersionDescription
	,getutcdate()
	)
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

COMMIT TRANSACTION
GO

IF @@ERROR <> 0
	SET NOEXEC ON
GO

DECLARE @Success AS BIT

SET @Success = 1
SET NOEXEC OFF

IF (@Success = 1)
	PRINT 'The database revert succeeded'
ELSE
BEGIN
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION

	PRINT 'The database revert failed'
END
GO