SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

DROP FULLTEXT INDEX ON [permit].[ORBC_PERMIT_DATA]
DROP FULLTEXT CATALOG PermitDataFTCat

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting Creation of Full Text Search Index on ORBC_PERMIT_DATA table.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (7, @VersionDescription, '$(FILE_HASH)', getutcdate())

COMMIT