SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
BEGIN TRANSACTION

ALTER TABLE [dbo].ORBC_ERROR DROP CONSTRAINT [ORBC_ERROR_USER_GUID_FK]
ALTER TABLE [dbo].ORBC_ERROR DROP CONSTRAINT [ORBC_ERROR_ERROR_TYPE_ID_FK]
DROP TABLE [dbo].[ORBC_ERROR_TYPE]
DROP TABLE [dbo].[ORBC_ERROR]

DECLARE @VersionDescription VARCHAR(255)
SET @VersionDescription = 'Reverting initial creation of entities for error.'

INSERT [dbo].[ORBC_SYS_VERSION] ([VERSION_ID], [DESCRIPTION], [DDL_FILE_SHA1], [RELEASE_DATE]) VALUES (8, @VersionDescription, '$(FILE_HASH)', getutcdate())

COMMIT