USE [master]
GO

CREATE DATABASE [onroutebc];
GO

USE [onroutebc]
GO
/****** Object:  Table [dbo].[ORT_COUNTRY]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_COUNTRY](
	[COUNTRY_ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRY_NAME] [varchar](50) NOT NULL,
	[COUNTRY_CODE] [char](2) NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[COUNTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_POWER_UNIT]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_POWER_UNIT](
	[POWER_UNIT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNIT_NUMBER] [nvarchar](10) NULL,
	[PLATE_NUMBER] [nvarchar](10) NOT NULL,
	[PROVINCE_STATE_REGISTERED] [int] NOT NULL,
	[YEAR] [smallint] NOT NULL,
	[MAKE] [nvarchar](50) NOT NULL,
	[VIN] [nvarchar](17) NOT NULL,
	[LICENSED_GVW] [numeric](18, 0) NOT NULL,
	[POWER_UNIT_TYPE] [int] NOT NULL,
	[STEER_AXLE_TIRE_SIZE] [int] NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_POWER_UNIT] PRIMARY KEY CLUSTERED 
(
	[POWER_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_POWER_UNIT_TYPE]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_POWER_UNIT_TYPE](
	[TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[POLICY_REFERENCE] [nvarchar](150) NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_POWER_UNIT_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_PROVINCE_STATE]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_PROVINCE_STATE](
	[PROVINCE_STATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROVINCE_STATE_NAME] [nvarchar](100) NOT NULL,
	[PROVINCE_STATE_CODE] [char](2) NOT NULL,
	[COUNTRY_ID] [int] NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_PROVINCE_STATE] PRIMARY KEY CLUSTERED 
(
	[PROVINCE_STATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_TRAILER]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_TRAILER](
	[TRAILER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNIT_NUMBER] [nvarchar](10) NULL,
	[PLATE_NUMBER] [nvarchar](10) NOT NULL,
	[PROVINCE_STATE_REGISTERED] [int] NOT NULL,
	[YEAR] [smallint] NOT NULL,
	[MAKE] [nvarchar](50) NOT NULL,
	[VIN] [varchar](17) NOT NULL,
	[TRAILER_TYPE] [int] NOT NULL,
	[TRAILER_SUBTYPE] [int] NULL,
	[EMPTY_TRAILER_WIDTH] [numeric](18, 0) NULL,
	[COMPANY_ID] [int] NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_TRAILER] PRIMARY KEY CLUSTERED 
(
	[TRAILER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_TRAILER_SUBTYPE]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_TRAILER_SUBTYPE](
	[SUBTYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBTYPE] [nvarchar](30) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[TYPE_ID] [int] NOT NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_TRAILER_SUBTYPE] PRIMARY KEY CLUSTERED 
(
	[SUBTYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORT_TRAILER_TYPE]    Script Date: 12/7/2022 9:25:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORT_TRAILER_TYPE](
	[TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[POLICY_REFERENCE] [nvarchar](150) NULL,
	[DB_CREATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_CREATE_USERID] [varchar](63) NOT NULL,
	[DB_LAST_UPDATE_TIMESTAMP] [datetime2](7) NOT NULL,
	[DB_LAST_UPDATE_USERID] [varchar](63) NOT NULL,
 CONSTRAINT [PK_ORT_TRAILER_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ORT_COUNTRY] ON 

INSERT [dbo].[ORT_COUNTRY] ([COUNTRY_ID], [COUNTRY_NAME], [COUNTRY_CODE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (1, N'Canada', N'CA', CAST(N'2022-12-07T20:40:40.6900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:40:40.6900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_COUNTRY] ([COUNTRY_ID], [COUNTRY_NAME], [COUNTRY_CODE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (2, N'United States', N'US', CAST(N'2022-12-07T20:40:49.8633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:40:49.8633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_COUNTRY] ([COUNTRY_ID], [COUNTRY_NAME], [COUNTRY_CODE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (3, N'Mexico', N'MX', CAST(N'2022-12-07T20:40:57.0633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:40:57.0633333' AS DateTime2), N'dbo')
SET IDENTITY_INSERT [dbo].[ORT_COUNTRY] OFF
GO
SET IDENTITY_INSERT [dbo].[ORT_POWER_UNIT_TYPE] ON 

INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (1, N'Buses/Crummies', N'A motor vehicle used to transport persons, when such transportation is not undertaken for compensation or gain.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_1.pdf', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (2, N'Concrete Pumper Trucks', N'Concrete Pumper Trucks are used to pump concrete from a cement mixer truck to where the concrete is actually needed. They travel on the highway at their equipped weight with no load.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (3, N'Cranes, Rubber-Tired Loaders, Firetrucks - All Terrain', N'Industrial vehicles not designed to transport load on highways.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (4, N'Cranes, Rubber-Tired Loaders, Firetrucks - Mobile', N'Industrial vehicles not designed to transport load on highways.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (5, N'Double Decker Buses', N'Double Decker buses are used primarily by the tourism industry.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (6, N'Farm Vehicles', N'A Farm Vehicle is a commercial vehicle owned and operated by a farmer, rancher or market gardener, the use of which is confined to purposes connected with his farm, ranch or market garden, including use for pleasure and is not used in connection with any other business in which the owner may be engaged.', N'http://www.icbc.com/vehicle-registration/specialty-vehicles/Documents/farm-vehicle.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (7, N'Fixed Equipment - Trucks/Graders etc.', N'Fixed Equipment means equipment bolted or welded to the truck or trailer, which was designed to perform certain engineered function(s), e.g. drilling derrick, vacuum bag house, and coil rig, etc., and may or may not include some incidental reducible load required for the intended function of the vehicle (such as the coil tubing in a coil tubing unit).', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (8, N'Intercity Buses (Pulling Pony Trailers)', N'Intercity Buses are vehicles designed to carry more than 15 passengers and equipped with facilities to allow extended travel without stopping.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (9, N'Logging Trucks', N'Logging Truck is a truck or truck and trailer combination used to haul, in their natural state, green felled or bucked logs or poles.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (10, N'Logging Trucks - Off-Highway', N'Logging Trucks - Off-Highway are permitted on an occasional basis from manufacturers to/from customers and to/from the bush for repairs etc., at maximum dimensions noted in Policy.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (11, N'Long Combination Vehicles (LCV) - Rocky Mountain Doubles', N'LCV vehicles for approved carriers and routes only.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (12, N'Long Combination Vehicles (LCV) - Turnpike Doubles', N'LCV vehicles for approved carriers and routes only.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (13, N'Long Wheelbase Truck Tractors Exceeding 6.2 m up to 7.25 m', N'Long Wheelbase Truck Tractors Exceeding 6.2 m up to 7.25 are vehicles that do not comply with wheelbase requirements indicated in CTR Appendix B', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (14, N'Oil and Gas - Bed Trucks', N'Bed Truck means a truck tractor equipped with a cargo carrying deck and a winch that is used for self loading and that is located behind the cab.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (15, N'Oil and Gas - Oilfield Sows', N'Oil and Gas - Oilfield Sows are vehicles that are exceptionally large truck-tractors equipped with a cargo carrying deck and winch located behind the cab used for loading and unloading in the oilfield.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (16, N'Oil and Gas - Service Rigs', N'Oil and Gas - Service Rigs are fixed equipment oilfield service trucks and includes rathole augers only equiped with heavy front projected crane (must exceed 14,000 kg tare weight).', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (17, N'Picker Truck Tractors', N'Picker Truck Tractors is a heavy duty crane mounted on a truck tractor or truck, considered permanently mounted equipment.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (18, N'Scrapers', N'A Scraper is a vehicle that is designed and used primarily for grading of highways, earth moving and other construction work on highways and that is not designed or used primarily for the transportation of persons or property, and that is only incidentally operated or moved over a highway.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (19, N'Tow Vehicles', N'Tow Vehicles means a motor vehicle used exclusively for towing or rendering assistance to other motor vehicles or to vehicles suffering from defects or disability in their means of locomotion.', N'http://www.bclaws.ca/civix/document/id/complete/statreg/30_78#AppendicesAtoK', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (20, N'Truck Tractors', N'Truck Tractor is a motor vehicle, having a net weight of more than 4,000 kg, that is equipped with a fifth-wheel coupler or a centre rotatable log bunk mounted on a bolster affixed to the vehicles chassis, and includes an auto carrier with an underslung fifth wheel coupler and a truck tractor with a load box.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (21, N'Truck Tractors - Stinger Steered', N'Truck Tractors - Stinger Steered are vehicles equipped with a rear mounted underslung fifth wheel and are considered a truck tractor similar to an auto carrier;', N'http://www.bclaws.ca/civix/document/id/complete/statreg/30_78#AppendicesAtoK', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (22, N'Trucks', N'A Truck is a motor vehicle, other than a bus, that is either permanently fitted with special equipment or is designed to and normally used to carry a load, and that may operate as a single unit or may pull a full trailer or pony trailer.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.1733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (23, N'Trucks Equipped with Front or Underbody Plow Blades', N'Vehicles not covered by the Highway Maintenance Agreement may be permitted to a width of 3.2 m.', NULL, CAST(N'2022-12-07T21:23:23.1733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.1733333' AS DateTime2), N'dbo')
SET IDENTITY_INSERT [dbo].[ORT_POWER_UNIT_TYPE] OFF
GO
SET IDENTITY_INSERT [dbo].[ORT_PROVINCE_STATE] ON 

INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (1, N'Alabama', N'AL', 2, CAST(N'2022-12-07T20:53:53.2533333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2533333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (2, N'Alaska', N'AK', 2, CAST(N'2022-12-07T20:53:53.2533333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2533333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (3, N'Arizona', N'AZ', 2, CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (4, N'Arkansas', N'AR', 2, CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (5, N'California', N'CA', 2, CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (6, N'Colorado', N'CO', 2, CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2566667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (7, N'Connecticut', N'CT', 2, CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (8, N'Delaware', N'DE', 2, CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (9, N'District of Columbia', N'DC', 2, CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (10, N'Florida', N'FL', 2, CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (11, N'Georgia', N'GA', 2, CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2600000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (12, N'Hawaii', N'HI', 2, CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (13, N'Idaho', N'ID', 2, CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (14, N'Illinois', N'IL', 2, CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (15, N'Indiana', N'IN', 2, CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2633333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (16, N'Iowa', N'IA', 2, CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (17, N'Kansas', N'KS', 2, CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (18, N'Kentucky', N'KY', 2, CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (19, N'Louisiana', N'LA', 2, CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (20, N'Maine', N'ME', 2, CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2666667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (21, N'Montana', N'MT', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (22, N'Nebraska', N'NE', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (23, N'Nevada', N'NV', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (24, N'New Hampshire', N'NH', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (25, N'New Jersey', N'NJ', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (26, N'New Mexico', N'NM', 2, CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2700000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (27, N'New York', N'NY', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (28, N'North Carolina', N'NC', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (29, N'North Dakota', N'ND', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (30, N'Ohio', N'OH', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (31, N'Oklahoma', N'OK', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (32, N'Oregon', N'OR', 2, CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2733333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (33, N'Maryland', N'MD', 2, CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (34, N'Massachusetts', N'MA', 2, CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (35, N'Michigan', N'MI', 2, CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (36, N'Minnesota', N'MN', 2, CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (37, N'Mississippi', N'MS', 2, CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2766667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (38, N'Missouri', N'MO', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (39, N'Pennsylvania', N'PA', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (40, N'Rhode Island', N'RI', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (41, N'South Carolina', N'SC', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (42, N'South Dakota', N'SD', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (43, N'Tennessee', N'TN', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (44, N'Texas', N'TX', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (45, N'Utah', N'UT', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (46, N'Vermont', N'VT', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (47, N'Virginia', N'VA', 2, CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2800000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (48, N'Washington', N'WA', 2, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (49, N'West Virginia', N'WV', 2, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (50, N'Wisconsin', N'WI', 2, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (51, N'Wyoming', N'WY', 2, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (52, N'Alberta', N'AB', 1, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (53, N'British Columbia', N'BC', 1, CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2833333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (54, N'Manitoba', N'MB', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (55, N'New Brunswick', N'NB', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (56, N'Newfoundland and Labrador', N'NL', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (57, N'Northwest Territories', N'NT', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (58, N'Nova Scotia', N'NS', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (59, N'Nunavut', N'NU', 1, CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (60, N'Ontario', N'ON', 1, CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (61, N'Prince Edward Island', N'PE', 1, CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (62, N'Quebec', N'QC', 1, CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (63, N'Saskatchewan', N'SK', 1, CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID], [PROVINCE_STATE_NAME], [PROVINCE_STATE_CODE], [COUNTRY_ID], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (64, N'Yukon', N'YT', 1, CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T20:53:53.2900000' AS DateTime2), N'dbo')
SET IDENTITY_INSERT [dbo].[ORT_PROVINCE_STATE] OFF
GO
SET IDENTITY_INSERT [dbo].[ORT_TRAILER_TYPE] ON 

INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (1, N'Boosters', N'A Booster is similar to a jeep, but it is used behind a load.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (2, N'Dollies', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5866667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5866667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (3, N'Expando Semi-Trailers', N'For use with Oil Field Bed Truck as power unit only. For other applications use Semi Trailer - Highboy or step deck, lowbed, expandos.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (4, N'Fixed Equipment - Conveyors (Pony Trailers)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (5, N'Fixed Equipment - Conveyors (Semi-Trailers)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (6, N'Fixed Equipment - Counter Flow Asphalt Drum Mixers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (7, N'Fixed Equipment - Pony Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (8, N'Fixed Equipment - Portable Asphalt Baghouses', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (9, N'Fixed Equipment - Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5900000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (10, N'Fixed Equipment - Wheeler Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (11, N'Float Trailers', N'See Commercial Transport Procedures Manual chapter 4.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_4.pdf', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (12, N'Full Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (13, N'Jeeps', N'Jeep means a semi-trailer that is designed to be attached between a truck tractor and another semi-trailer, so as to distribute the load of the other semi-trailer between the axles of the jeep and axles of the truck tractor.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (14, N'Legacy Logging Trailer Combinations - Non-TAC B-Trains', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5933333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (15, N'Legacy Logging Trailer Combinations - Single Axle Jeeps, Tandem Axle Pole Trailers, Dogloggers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (16, N'Legacy Logging Trailer Combinations - Single Axle Jeeps, Tri Axle Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (17, N'Legacy Logging Trailer Combinations - Tandem Pole Trailers, Dogloggers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (18, N'Logging Semi-Trailer - Empty, 3.2 m Bunks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.5966667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (19, N'Logging Trailers - Full Trailers, Tri Axle, Quad Axle', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (20, N'Logging Trailers - Overwidth Bunks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (21, N'None', N'Select "None" if no trailer is required and only the power unit is being permitted.', NULL, CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (22, N'Oil and Gas - Oversize Oilfield Flat Deck Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (23, N'Overdimensional Trailers and Semi-Trailers (For Export)', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (24, N'Platform Trailers', N'Extraordinary Loads Only (currently platform trailers require extraordinary load approval).', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_6.pdf', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6000000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (25, N'Pole Trailers', N'CTR Appendices H and I – plus legacy vehicles from 5.3.7.C including doglogger and sjostrom trailer.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (26, N'Pony Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (27, N'Ready Mix Concrete Pump Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (28, N'Semi-Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (29, N'Semi-Trailers - A-Trains and C-Trains', N'A-Train means a combination of vehicles composed of a truck tractor, a semi-trailer and either, (a) an A dolly and a semi-trailer, or (b) a full trailer.    C-Train means a combination of vehicles composed of a truck tractor and a semi-trailer, followed by another semi-trailer attached to the first semi-trailer by the means of a C dolly or C converter dolly.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_4.pdf', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6033333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (30, N'Semi-Trailers - B-Trains', N'B-trains for transporting reducible or non reducible loads other than wood chip residual.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_4.pdf', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (31, N'Semi-Trailers - Hiboys/Expandos', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (32, N'Semi-Trailers - Hiboys/Flat Decks', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (33, N'Semi-Trailers - Insulated Vans with Reefer/Refrigeration Units', N'See commercial transport procedures manual chapter 5.1 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6066667' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (34, N'Semi-Trailers - Logging', N'See Commercial Transport Procedures Manual chapter 4.5 for details.', NULL, CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (35, N'Semi-Trailers - Non-Tac Short Chassis', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (36, N'Semi-Trailers - Single Drop, Double Drop, Step Decks, Lowbed, Expandos, etc.', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (37, N'Semi-Trailers - Steering Trailers', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (38, N'Semi-Trailers - Stinger Steered Automobile Transporters', N'See Commercial Transport Procedures Manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (39, N'Semi-Trailers - Walled B-Trains (Chip Trucks)', N'See Commercial Transport Procedures Manual chapter 4.5.1 for details', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_4.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (40, N'Semi-Trailers - Wheelers', N'Note that at this time, wheeler semi-trailers need extraordinary load approvals except on the pre-approved wheeler 85 tonne routes from 6.3.3.D (different from the other 85 tonne routes)).', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6100000' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (41, N'Semi-Trailers - Wide Wheelers', N'Extraordinary Loads Only (currently wide wheelers require extraordinary load approval).', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (42, N'Semi-Trailers - Widespread Tandems', NULL, NULL, CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (43, N'Semi-Trailers with Crane', N'See commercial transport procedures manual chapter 5.3 for details.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (44, N'Steering Trailers - Manned', N'Treated as a semi-trailer axle group and a booster in the Heavy Haul Quick Reference Chart, but with a requirement that the number of axles in the frst axle group cannot exceed the number of axles in the second axle group.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (45, N'Steering Trailers - Self/Remote', N'Treated as a semi-trailer axle group and a booster in the Heavy Haul Quick Reference Chart, but with a requirement that the number of axles in the first axle group cannot exceed the number of axles in the second axle group.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_5.pdf', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6133333' AS DateTime2), N'dbo')
INSERT [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID], [TYPE], [DESCRIPTION], [POLICY_REFERENCE], [DB_CREATE_TIMESTAMP], [DB_CREATE_USERID], [DB_LAST_UPDATE_TIMESTAMP], [DB_LAST_UPDATE_USERID]) VALUES (46, N'Tandem/Tridem Drive B-Train (Super B-Train)', N'B-trains for wood chip residual.', N'http://www.th.gov.bc.ca/cvse/ctpm/Chapter_4.pdf', CAST(N'2022-12-07T21:23:23.6166667' AS DateTime2), N'dbo', CAST(N'2022-12-07T21:23:23.6166667' AS DateTime2), N'dbo')
SET IDENTITY_INSERT [dbo].[ORT_TRAILER_TYPE] OFF
GO
ALTER TABLE [dbo].[ORT_COUNTRY] ADD  CONSTRAINT [DF_ORT_COUNTRY_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_COUNTRY] ADD  CONSTRAINT [DF_ORT_COUNTRY_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_COUNTRY] ADD  CONSTRAINT [DF_ORT_COUNTRY_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_COUNTRY] ADD  CONSTRAINT [DF_ORT_COUNTRY_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_TYPE_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_TYPE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_TYPE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT_TYPE] ADD  CONSTRAINT [DF_ORT_POWER_UNIT_TYPE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE] ADD  CONSTRAINT [DF_ORT_PROVINCE_STATE_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE] ADD  CONSTRAINT [DF_ORT_PROVINCE_STATE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE] ADD  CONSTRAINT [DF_ORT_PROVINCE_STATE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE] ADD  CONSTRAINT [DF_ORT_PROVINCE_STATE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER] ADD  CONSTRAINT [DF_ORT_TRAILER_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER] ADD  CONSTRAINT [DF_ORT_TRAILER_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER] ADD  CONSTRAINT [DF_ORT_TRAILER_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER] ADD  CONSTRAINT [DF_ORT_TRAILER_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_SUBTYPE_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_SUBTYPE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_SUBTYPE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_SUBTYPE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_TYPE_DB_CREATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_CREATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_TYPE_DB_CREATE_USERID]  DEFAULT (user_name()) FOR [DB_CREATE_USERID]
GO
ALTER TABLE [dbo].[ORT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_TYPE_DB_LAST_UPDATE_TIMESTAMP]  DEFAULT (getdate()) FOR [DB_LAST_UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[ORT_TRAILER_TYPE] ADD  CONSTRAINT [DF_ORT_TRAILER_TYPE_DB_LAST_UPDATE_USERID]  DEFAULT (user_name()) FOR [DB_LAST_UPDATE_USERID]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT]  WITH CHECK ADD  CONSTRAINT [FK_ORT_POWER_UNIT_POWER_UNIT_TYPE] FOREIGN KEY([POWER_UNIT_TYPE])
REFERENCES [dbo].[ORT_POWER_UNIT_TYPE] ([TYPE_ID])
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] CHECK CONSTRAINT [FK_ORT_POWER_UNIT_POWER_UNIT_TYPE]
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT]  WITH CHECK ADD  CONSTRAINT [FK_ORT_POWER_UNIT_PROVINCE_STATE] FOREIGN KEY([PROVINCE_STATE_REGISTERED])
REFERENCES [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID])
GO
ALTER TABLE [dbo].[ORT_POWER_UNIT] CHECK CONSTRAINT [FK_ORT_POWER_UNIT_PROVINCE_STATE]
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE]  WITH CHECK ADD  CONSTRAINT [FK_ORT_PROVINCE_STATE_COUNTRY] FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[ORT_COUNTRY] ([COUNTRY_ID])
GO
ALTER TABLE [dbo].[ORT_PROVINCE_STATE] CHECK CONSTRAINT [FK_ORT_PROVINCE_STATE_COUNTRY]
GO
ALTER TABLE [dbo].[ORT_TRAILER]  WITH CHECK ADD  CONSTRAINT [FK_ORT_TRAILER_PROVINCE_STATE] FOREIGN KEY([PROVINCE_STATE_REGISTERED])
REFERENCES [dbo].[ORT_PROVINCE_STATE] ([PROVINCE_STATE_ID])
GO
ALTER TABLE [dbo].[ORT_TRAILER] CHECK CONSTRAINT [FK_ORT_TRAILER_PROVINCE_STATE]
GO
ALTER TABLE [dbo].[ORT_TRAILER]  WITH CHECK ADD  CONSTRAINT [FK_ORT_TRAILER_TRAILER_SUBTYPE] FOREIGN KEY([TRAILER_SUBTYPE])
REFERENCES [dbo].[ORT_TRAILER_SUBTYPE] ([SUBTYPE_ID])
GO
ALTER TABLE [dbo].[ORT_TRAILER] CHECK CONSTRAINT [FK_ORT_TRAILER_TRAILER_SUBTYPE]
GO
ALTER TABLE [dbo].[ORT_TRAILER]  WITH CHECK ADD  CONSTRAINT [FK_ORT_TRAILER_TRAILER_TYPE] FOREIGN KEY([TRAILER_TYPE])
REFERENCES [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID])
GO
ALTER TABLE [dbo].[ORT_TRAILER] CHECK CONSTRAINT [FK_ORT_TRAILER_TRAILER_TYPE]
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE]  WITH CHECK ADD  CONSTRAINT [FK_ORT_TRAILER_SUBTYPE_TRAILER_TYPE] FOREIGN KEY([TYPE_ID])
REFERENCES [dbo].[ORT_TRAILER_TYPE] ([TYPE_ID])
GO
ALTER TABLE [dbo].[ORT_TRAILER_SUBTYPE] CHECK CONSTRAINT [FK_ORT_TRAILER_SUBTYPE_TRAILER_TYPE]
GO
USE [master]
GO
ALTER DATABASE [onroutebc] SET  READ_WRITE 
GO
