export const CaseEventType = {
  OPENED: 'OPENED',
  CLOSED: 'CLOSED',
  ASSIGNED: 'ASSIGNED',
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  CASE_WITHDRAWN: 'CASE_WITHDRAWN',
  NOTE_CREATED: 'NOTE_CREATED',
  DOCUMENT_ADDED: 'DOCUMENT_ADDED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  NOTIFICATION: 'NOTIFICATION',
} as const;

export type CaseEventType = (typeof CaseEventType)[keyof typeof CaseEventType];
