export enum CreditAccountActivityType {
  ACCOUNT_ON_HOLD = 'ONHOLD',
  ACCOUNT_HOLD_REMOVED = 'HOLDRMVD',
  ACCOUNT_CLOSED = 'CLOSED',
  ACCOUNT_REOPENED = 'REOPENED',
  ACCOUNT_OPENED = 'OPENED',
  ACCOUNT_MIGRATED = 'MIGRATED',
  ACCOUNT_VERIFIED = 'VERIFIED',
}
