export enum UserAuthGroup {
  ANONYMOUS = 'ANONYMOUS',
  CV_CLIENT = 'CVCLIENT',
  IDIR_BASIC_USER = 'IDIRBASIC',
  COMPANY_ADMINISTRATOR = 'ORGADMIN',
  PPC_CLERK = 'PPCCLERK',
  PUBLIC_VERIFIED = 'PUBLIC',
  SYSTEM_ADMINISTRATOR = 'SYSADMIN',
  ENFORCEMENT_OFFICER = 'EOFFICER',
}
