import {
  POLICY_CHECK_ID_TYPES,
  PolicyCheckIdType,
} from "../../../../../../types/AxleCalculationResult";

// Results remain filtered until every policy-engine evaluation has a defined
// frontend presentation.
export const DISPLAYABLE_POLICY_CHECK_IDS = new Set<PolicyCheckIdType>([
  POLICY_CHECK_ID_TYPES.AXLE_GROUP_MAXIMUM_LEGAL_WEIGHT_THRESHOLD,
  POLICY_CHECK_ID_TYPES.BOOSTER_AXLE_LIMIT,
  POLICY_CHECK_ID_TYPES.BRIDGE_FORMULA,
  POLICY_CHECK_ID_TYPES.DRIVE_JEEP_LOAD_EQUALIZATION,
  POLICY_CHECK_ID_TYPES.LEGAL_AXLE_SPREAD,
  POLICY_CHECK_ID_TYPES.LEGAL_INTERAXLE_SPACING,
  POLICY_CHECK_ID_TYPES.LEGAL_WEIGHT,
  POLICY_CHECK_ID_TYPES.MINIMUM_STEER_AXLE_WEIGHT,
  POLICY_CHECK_ID_TYPES.MINIMUM_TANDEM_STEER_AXLE_WEIGHT,
  POLICY_CHECK_ID_TYPES.MINIMUM_DRIVE_AXLE_WEIGHT,
  POLICY_CHECK_ID_TYPES.NUMBER_OF_AXLES,
  POLICY_CHECK_ID_TYPES.NUMBER_OF_WHEELS_PER_AXLE,
  POLICY_CHECK_ID_TYPES.MAX_TIRE_LOAD,
  POLICY_CHECK_ID_TYPES.PERMITTABLE_WEIGHT,
  POLICY_CHECK_ID_TYPES.PICKER_TRUCK_TRACTOR_WEIGHT_RESTRICTIONS,
  POLICY_CHECK_ID_TYPES.WHEELBASE_LEGAL_LIMITS,
]);
