-- Test that the trigger sets the correct permit number, and
-- that the previous rev id is set correctly
SET NOCOUNT ON
INSERT INTO $(DB_NAME).tps.ORBC_TPS_MIGRATED_PERMITS(
	PERMIT_TYPE,
	START_DATE,
	END_DATE,
	ISSUED_DATE,
	CLIENT_HASH,
	PLATE,
	VIN,
	PERMIT_NUMBER,
	NEW_PERMIT_NUMBER,
	PERMIT_GENERATION,
	SERVICE)
VALUES(
	'TROS',
	'20240101',
	'20240201',
	'20240101 12:00:00PM',
	'HASH',
	'TSTPLT2',
	'TSTVIN',
	'08-100-3429',
	'P0-08100342-911-A01', -- changing the incoming permit number to test
	2, -- previous revision was 1, this is next one
	'C')

SELECT COUNT(*) FROM $(DB_NAME).permit.ORBC_PERMIT 
WHERE 
  PERMIT_NUMBER = 'P0-08100342-900-A01'
AND
  REVISION = 1
AND 
  PERMIT_APPROVAL_SOURCE_TYPE = 'TPS'
AND
  ORIGINAL_ID = (SELECT ID FROM $(DB_NAME).permit.ORBC_PERMIT WHERE PERMIT_NUMBER = 'P0-08100342-900')
AND
	PERMIT_STATUS_TYPE = 'ISSUED'
AND 
	PREVIOUS_REV_ID = (SELECT ID FROM $(DB_NAME).permit.ORBC_PERMIT WHERE PERMIT_NUMBER = 'P0-08100342-900')