-- Test that the trigger sets previous revision to SUPERSEDED
SET NOCOUNT ON
SELECT COUNT(*) FROM $(DB_NAME).permit.ORBC_PERMIT 
WHERE 
  PERMIT_NUMBER = 'P0-08100342-900'
AND
  REVISION = 0
AND 
  PERMIT_APPROVAL_SOURCE_TYPE = 'TPS'
AND
	PERMIT_STATUS_TYPE = 'SUPERSEDED'