SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_USER]', 'U') IS NOT NULL AND
   OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY]', 'U') IS NOT NULL AND
   OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_TYPE]', 'U') IS NOT NULL AND
   OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT]', 'U') IS NOT NULL AND
   OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_TYPE]', 'U') IS NOT NULL AND
   OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_STATUS_TYPE]', 'U') IS NOT NULL AND   
    SELECT 1 
ELSE
    SELECT 0
