SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_POLICY_CONFIGURATION]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_POLICY_CONFIGURATION_HIST]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0