SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_ACTIVITY_HIST]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_HIST]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[permit].[ORBC_CREDIT_ACCOUNT_USER_HIST]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0