SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_POWER_UNIT]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_TRAILER]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_COUNTRY_TYPE]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_POWER_UNIT_TYPE]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_PROVINCE_TYPE]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_TRAILER_TYPE]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0