-- Test that the role types have been inserted correctly against user auth groups
SET NOCOUNT ON

IF (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_SPECIAL_AUTH_DB_CREATE_USERID]','D') IS NOT NULL) 
AND OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_SPECIAL_AUTH_DB_CREATE_TIMESTAMP]','D') IS NOT NULL
AND (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_SPECIAL_AUTH_DB_LAST_UPDATE_USERID]','D') IS NOT NULL) 
AND (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_SPECIAL_AUTH_DB_LAST_UPDATE_TIMESTAMP]','D') IS NOT NULL) 
AND (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_NO_FEE_TYPE_DB_CREATE_USERID]','D') IS NOT NULL) 
AND OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_NO_FEE_TYPE_DB_CREATE_TIMESTAMP]','D') IS NOT NULL
AND (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_NO_FEE_TYPE_DB_LAST_UPDATE_USERID]','D') IS NOT NULL) 
AND (OBJECT_ID('[$(DB_NAME)].[permit].[DF_ORBC_NO_FEE_TYPE_DB_LAST_UPDATE_TIMESTAMP]','D') IS NOT NULL) 
    SELECT 1 
ELSE
    SELECT 0