SET NOCOUNT ON
IF OBJECT_ID('[$(MSSQL_DB)].[dbo].[ORBC_COMPANY]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(MSSQL_DB)].[dbo].[ORBC_MM_COMPANY_USER]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(MSSQL_DB)].[dbo].[ORBC_USER]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(MSSQL_DB)].[dbo].[ORBC_VT_DIRECTORY]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0