SET NOCOUNT ON

SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] ON 
INSERT INTO $(DB_NAME).permit.ORBC_PERMIT(ID, PERMIT_TYPE_ID, APPLICATION_ORIGIN_ID) VALUES(1, 'TROS', 'ONLINE')
SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] OFF

SELECT APPLICATION_NUMBER FROM $(DB_NAME).permit.ORBC_PERMIT WHERE ID = 1

-- Clean up
DELETE FROM $(DB_NAME).[permit].[ORBC_PERMIT_STATE]
DELETE FROM $(DB_NAME).[permit].[ORBC_PERMIT]