SET NOCOUNT ON

SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] ON 
INSERT INTO $(DB_NAME).permit.ORBC_PERMIT(ID, PERMIT_TYPE_ID, APPLICATION_ORIGIN_ID, PERMIT_APPROVAL_SOURCE_ID, APPLICATION_NUMBER, PERMIT_NUMBER) VALUES(44, 'TROS', 'ONLINE', 'PPC', 'A2-00000044-321', 'P1-00000044-123')
INSERT INTO $(DB_NAME).permit.ORBC_PERMIT(ID, PERMIT_TYPE_ID, APPLICATION_ORIGIN_ID, REVISION, PREVIOUS_REV_ID) VALUES(45, 'TROS', 'ONLINE', 1, 44)
SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] OFF

SELECT APPLICATION_NUMBER FROM $(DB_NAME).permit.ORBC_PERMIT WHERE ID = 45

-- Clean up
DELETE FROM $(DB_NAME).[permit].[ORBC_PERMIT]