SET NOCOUNT ON

SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] ON 
INSERT INTO $(DB_NAME).permit.ORBC_PERMIT(ID, PERMIT_TYPE_ID, APPLICATION_ORIGIN_ID) VALUES(33, 'TROS', 'ONLINE')
SET IDENTITY_INSERT $(DB_NAME).[permit].[ORBC_PERMIT] OFF

SELECT PERMIT_STATUS_ID FROM $(DB_NAME).permit.ORBC_PERMIT_STATE WHERE PERMIT_ID = 33

-- Clean up
DELETE FROM $(DB_NAME).[permit].[ORBC_PERMIT_STATE]
DELETE FROM $(DB_NAME).[permit].[ORBC_PERMIT]