SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[tps].[LEGACY_TPS_CLIENT_DATA]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ORBC_TPS_MIGRATED_PERMITS]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0