SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[tps].[ORBC_TPS_MIGRATED_CLIENTS]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ORBC_TPS_MIGRATED_PERMITS]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ORBC_TPS_MIGRATED_USERS]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ETL_PROCESS_ERROR]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ETL_PROCESSES]', 'U') IS NOT NULL 
AND OBJECT_ID('[$(DB_NAME)].[tps].[ETL_PROCESS_TYPE]', 'U') IS NOT NULL 
    SELECT 1 
ELSE
    SELECT 0