---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
data: 
  {{- include "service.configmap" . | nindent 2 }}
