apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "service.fullname" . }}
        from:
          kind: ImageStreamTag
          name: {{ include "service.fullname" . }}:{{ .Values.image.tag }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  strategy:
    type: Rolling
  template:
    metadata:
      annotations:
        {{- include "service.podAnnotations" . | nindent 8 }}
        {{- include "service.vaultAnnotations" . | nindent 8 }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{.Values.serviceAccountName}}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - image: {{ include "service.fullname" . }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ include "service.fullname" . }}
          {{- if .Values.vault.enabled}}
          args:
            - 'sh' 
            - '-c'
            - '{{- range $k := .Values.vault.secrets }}source /vault/secrets/{{$k}} && {{- end}}{{ .Values.vault.entrypoint }}'
          {{- end}}
          env:
          {{- range $k,$v := fromYaml (.Values.configmap.env) }}
            - name: {{$k}}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.fullname" $ }}
                  key: {{$k}}
          {{- end }}
          {{- range $k,$v := fromYaml (.Values.secret.stringdata) }}
            - name: {{$k}}
              valueFrom:
                secretKeyRef:
                  name: {{ include "service.fullname" $ }}
                  key: {{$k}}
          {{- end }}
            - name: TIMESTAMP
              value: "{{ now | toString }}"
          ports:
            {{- toYaml .Values.container.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          readinessProbe: 
            {{  toYaml .Values.container.readinessProbe | nindent 12 }}
          livenessProbe:
            {{  toYaml .Values.container.livenessProbe | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.container.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
