---
{{- if .Values.imagestream.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: {{ .Values.image.tag }}
      from:
        kind: DockerImage
        name: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      referencePolicy:
        type: Local
{{- end }}
