---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
  name: {{ include "service.fullname" . }}
stringData: 
{{- include "service.secret" . | nindent 2}}
