apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: onroutebc
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
  - name: LICENSE_PLATE
    description: The BC GOV LICENSE_PLATE for this project
    required: true
  - name: VAULT_ENVIRONMENT
    description: The Vault environment for this project
    required: true
  - name: VAULT_ZONE
    description: Using Dev/Test/etc.. within vault
    required: true
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
