apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: onroutebc
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
  - name: DATABASE_NAME
    description: Name of Database to connect to 
    required: true
  - name: DATABASE_USER
    description: User connecting to database
    required: true
  - name: DATABASE_PASSWORD
    description: Password of user connecting to database
    required: true
  - name: DATABASE_HOST
    description: Host url/service of database connection
    required: true
  - name: CHES_CLIENT_ID
    description: Client Id to request the access token for connecting to CHES
    required: true
  - name: CHES_CLIENT_SECRET
    description: Client Secret to request the access token for connecting to CHES
    required: true
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
