apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: onroutebc
  - name: NAMESPACE
    description: Deployment environment namespace
    required: false
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
  - name: DATABASE_NAME
    description: Name of Database to connect to 
    required: true
  - name: DATABASE_USER
    description: User connecting to database
    required: true
  - name: DATABASE_PASSWORD
    description: Password of user connecting to database
    required: true
  - name: DATABASE_HOST
    description: Host url/service of database connection
    required: true
  - name: AUTH0_ISSUER_URL
    description: The principal that issued the JWT
    required: true
  - name: AUTH0_AUDIENCE
    description: Identifies the recipients that the JWT is intended for
    required: true
  - name: AUTH0_IGNORE_EXP
    description: The boolean flag to ignore the JWT expiration
    required: true    
  - name: BASICAUTH_USERNAME
    description: The basic auth username for COMS
    required: true
  - name: BASICAUTH_PASSWORD
    description: The basic auth password for COMS
    required: true
  - name: COMS_URL
    description: The URL for the deployed instance of COMS
    required: true
  - name: COMS_SERVICE
    description: The identifier to determine whether COMS is hosted vs self-hosted
    required: true
  - name: COMS_BUCKET_ID
    description: The Uuid representing the bucket
    required: true
  - name: COMS_PRESIGNED_URL_EXPIRY
    description: The exipry value (seconds) of the presigned URL
    required: true
  - name: CDOGS_CLIENT_ID
    description: The keycloak client ID for common hosted CDOGS
    required: true
  - name: CDOGS_CLIENT_SECRET
    description: The keycloak client secret for common hosted CDOGS
    required: true
  - name: CDOGS_TOKEN_URL
    description: The keycloak url for common hosted CDOGS
    required: true
  - name: CDOGS_URL
    description: The CDOGS API url 
    required: true
  - name: CHES_TOKEN_URL
    description: The keycloak url for common hosted CHES
    required: true    
  - name: CHES_CLIENT_ID
    description: Client Id to request the access token for connecting to CHES
    required: true
  - name: CHES_CLIENT_SECRET
    description: Client Secret to request the access token for connecting to CHES
    required: true
  - name: CHES_URL
    description: The CHES API url
  - name: NODE_ENV
    description: The NODE Environment
    required: true    
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
