apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: onroutebc
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PROMOTE
    description: Dummy param, for convenience in deployments
  - name: DATABASE_NAME
    description: Name of Database to connect to 
    required: false
  - name: DATABASE_USER
    description: User connecting to database
    required: false
  - name: DATABASE_PASSWORD
    description: Password of user connecting to database
    required: false
  - name: DATABASE_HOST
    description: Host url/service of database connection
    required: false
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${DATABASE_NAME}
    data:
      database-name: "${DATABASE_NAME}"
      database-host: "${DATABASE_HOST}"
      database-encrypt: "false"
      database-port: "1433" 
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${DATABASE_NAME}
    data:
      database-user: "${DATABASE_USER}"
      database-password: "${DATABASE_PASSWORD}"
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
