SET NOCOUNT ON
GO
SET IDENTITY_INSERT [dbo].[ORBC_PDF_TEMPLATE] ON 

INSERT [dbo].[ORBC_PDF_TEMPLATE] ([TEMPLATE_ID], [TEMPLATE_NAME], [PERMIT_TYPE_ID], [TEMPLATE_VERSION], [DMS_REF_ID]) VALUES (1, N'TROS', N'TROS', N'latest', 1)
GO

SET IDENTITY_INSERT [dbo].[ORBC_PDF_TEMPLATE] OFF
GO