SET NOCOUNT ON
GO
SET IDENTITY_INSERT [dbo].[ORBC_PDF_TEMPLATE] ON 

INSERT [dbo].[ORBC_PDF_TEMPLATE] ([TEMPLATE_ID], [TEMPLATE_NAME], [TEMPLATE_VERSION], [COMS_REF_ID]) VALUES (1, N'TROS', N'latest', 1)
GO

SET IDENTITY_INSERT [dbo].[ORBC_PDF_TEMPLATE] OFF
GO