SET NOCOUNT ON
GO
SET IDENTITY_INSERT [dbo].[ORBC_DOCUMENT_TEMPLATE] ON 

INSERT [dbo].[ORBC_DOCUMENT_TEMPLATE] ([TEMPLATE_ID], [TEMPLATE_NAME], [TEMPLATE_VERSION], [DOCUMENT_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (1, N'TROS', 1, 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO

SET IDENTITY_INSERT [dbo].[ORBC_DOCUMENT_TEMPLATE] OFF
GO