SET NOCOUNT ON
GO
SET IDENTITY_INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ON 

INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (1, N'CVSE1000', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1251', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (2, N'CVSE1000L', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1250', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (3, N'CVSE1000S', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1255', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (4, N'CVSE1001', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1252', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (5, N'CVSE1002', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1253', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (6, N'CVSE1010', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1257', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (7, N'CVSE1011', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1258', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (8, N'CVSE1012', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1259', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (9, N'CVSE1013', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1254', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (10, N'CVSE1014', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1260', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (11, N'CVSE1016', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1462', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (12, N'CVSE1020', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1266', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (13, N'CVSE1021', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1272', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (14, N'CVSE1022', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1271', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (15, N'CVSE1040', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1445', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (16, N'CVSE1049', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1262', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (17, N'CVSE1052', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1265', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (18, N'CVSE1053', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1433', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (19, N'CVSE1054', N'https://gww.th.gov.bc.ca/forms/getFormRedirect.aspx?fDomain=1&formId=1438', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (20, N'CVSE1060', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1268', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (21, N'CVSE1061', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1269', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO
INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] ([ID], [DOCUMENT_NAME], [DOCUMENT_LOCATION], [DOCUMENT_MIME_TYPE], [DOCUMENT_VERSION_ID], [CONCURRENCY_CONTROL_NUMBER], [DB_CREATE_USERID], [DB_CREATE_TIMESTAMP], [DB_LAST_UPDATE_USERID], [DB_LAST_UPDATE_TIMESTAMP]) VALUES (22, N'CVSE1070', N'https://www.th.gov.bc.ca/forms/getForm.aspx?formId=1261', N'application/pdf', 1, 1, N'dops', GETUTCDATE(), N'dops', GETUTCDATE())
GO

SET IDENTITY_INSERT [dops].[ORBC_EXTERNAL_DOCUMENT] OFF
GO