SET NOCOUNT ON
GO
SET QUOTED_IDENTIFIER ON
GO

INSERT INTO permit.ORBC_PERMIT (
  COMPANY_ID, 
  PERMIT_TYPE, 
  PERMIT_APPROVAL_SOURCE_TYPE, 
  PERMIT_NUMBER, 
  TPS_PERMIT_NUMBER, 
  REVISION, 
  PERMIT_STATUS_TYPE, 
  PERMIT_ISSUE_DATE_TIME)
VALUES (
  4,
  'TROS',
  'TPS',
  'P0-12345678-004',
  '08-002-0004',
  0,
  'ISSUED',
  GETDATE())

INSERT INTO permit.ORBC_PERMIT (
  COMPANY_ID, 
  PERMIT_TYPE, 
  PERMIT_APPROVAL_SOURCE_TYPE, 
  PERMIT_NUMBER, 
  TPS_PERMIT_NUMBER, 
  REVISION, 
  PERMIT_STATUS_TYPE, 
  PERMIT_ISSUE_DATE_TIME)
VALUES (
  5,
  'TROS',
  'TPS',
  'P0-12345678-005',
  '08-002-0005',
  0,
  'ISSUED',
  GETDATE())

INSERT INTO permit.ORBC_PERMIT (
  COMPANY_ID, 
  PERMIT_TYPE, 
  PERMIT_APPROVAL_SOURCE_TYPE, 
  PERMIT_NUMBER, 
  TPS_PERMIT_NUMBER, 
  REVISION, 
  PERMIT_STATUS_TYPE, 
  PERMIT_ISSUE_DATE_TIME)
VALUES (
  6,
  'TROS',
  'TPS',
  'P0-12345678-006',
  '08-002-0006',
  0,
  'ISSUED',
  GETDATE())

INSERT INTO permit.ORBC_PERMIT (
  COMPANY_ID, 
  PERMIT_TYPE, 
  PERMIT_APPROVAL_SOURCE_TYPE, 
  PERMIT_NUMBER, 
  TPS_PERMIT_NUMBER, 
  REVISION, 
  PERMIT_STATUS_TYPE, 
  PERMIT_ISSUE_DATE_TIME)
VALUES (
  7,
  'TROS',
  'TPS',
  'P0-12345678-007',
  '08-002-0007',
  0,
  'ISSUED',
  GETDATE())

GO