SET NOCOUNT ON
GO
SET QUOTED_IDENTIFIER ON
GO

INSERT INTO permit.ORBC_CREDIT_ACCOUNT (
  COMPANY_ID,
  CREDIT_ACCOUNT_STATUS_TYPE,
  CREDIT_ACCOUNT_TYPE,
  CREDIT_ACCOUNT_NUMBER,
  IS_VERIFIED
) VALUES (
  '74',
  'ACTIVE',
  'UNKNOWN',
  'WS1689',
  'N'
);

INSERT INTO permit.ORBC_CREDIT_ACCOUNT_ACTIVITY (
  CREDIT_ACCOUNT_ID,
  DATE,
  CREDIT_ACCOUNT_ACTIVITY_TYPE,
  COMMENTS
) VALUES (
  SCOPE_IDENTITY(),
  GETUTCDATE(),
  'MIGRATED',
  'Action initiated in TPS'
);

GO