SET NOCOUNT ON
IF OBJECT_ID('[$(DB_NAME)].[dbo].[ORBC_SYS_VERSION]', 'U') IS NOT NULL
    SELECT TOP 1 VERSION_ID FROM [$(DB_NAME)].[dbo].[ORBC_SYS_VERSION] ORDER BY MIGRATION_ID DESC
ELSE
    SELECT 0