---
apiVersion: v2
name: onRouteBC
description: Helm chart for onRouteBC
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies: # A list of the chart requirements (optional)
  - name: component
    repository: "file:///home/ubuntu/helm-service/charts/component/"
    alias: frontend
    version: 0.0.2
  - name: component
    repository: "file:///home/ubuntu/helm-service/charts/component/"
    alias: vehicles
    version: 0.0.2
  - name: component
    repository: "file:///home/ubuntu/helm-service/charts/component/"
    alias: dops
    version: 0.0.2
