apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: onroutebc
  - name: COMPONENT
    description: Component name
    value: backend-dops
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: "25m"
  - name: MEMORY_REQUEST
    value: "50Mi"
  - name: CPU_LIMIT
    value: "75m"
  - name: MEMORY_LIMIT
    value: "150Mi"
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "5"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/onroutebc:prod-backend-dops
  - name: DATABASE_NAME
    description: Name of Database to connect to 
    required: true
  - name: DATABASE_USER
    description: User connecting to database
    required: true
  - name: DATABASE_PASSWORD
    description: Password of user connecting to database
    required: true
  - name: DATABASE_HOST
    description: Host url/service of database connection
    required: true
  - name: AUTH0_ISSUER_URL
    description: The principal that issued the JWT
    required: true
  - name: AUTH0_AUDIENCE
    description: Identifies the recipients that the JWT is intended for
    required: true
  - name: AUTH0_IGNORE_EXP
    description: The boolean flag to ignore the JWT expiration
    required: true
  - name: SITEMINDER_LOG_OFF_URL
    description: The siteminder log off url
    required: true
  - name: CFS_PRIVATE_KEY
    description: The private key to connect to cfs sftp server
    required: true
  - name: CFS_PASSPHRASE
    description: The passphrase for cfs_private_key
    required: true
  - name: DOPS_CVSE_FORMS_CACHE_TTL_MS
    description: The cache time to live for CVSE FORMS in DOPS in Milliseconds
    required: true
  - name: DOPS_S3_ACCESS_TYPE
    description: The key to switch between COMS or Direct access
    required: true
  - name: DOPS_S3_ACCESSKEYID
    description: The Access Key for your S3 compatible object storage account
    required: true
  - name: DOPS_S3_BUCKET
    description: The object storage bucket name
    required: true
  - name: DOPS_S3_PRESIGNED_URL_EXPIRY
    description: The expiry time for pre-signed URLs to objects in seconds
    required: true
  - name: DOPS_S3_ENDPOINT
    description: Object store URL
    required: true
  - name: DOPS_S3_KEY
    description: The base path for storage location
    required: true
  - name: DOPS_S3_SECRETACCESSKEY
    description: The Secret Access Key for your S3 compatible object storage account
    required: true
  - name: CDOGS_CLIENT_ID
    description: The keycloak client ID for common hosted CDOGS
    required: true
  - name: CDOGS_CLIENT_SECRET
    description: The keycloak client secret for common hosted CDOGS
    required: true
  - name: CDOGS_TOKEN_URL
    description: The keycloak url for common hosted CDOGS
    required: true
  - name: CDOGS_URL
    description: The CDOGS API url 
    required: true
  - name: CHES_TOKEN_URL
    description: The keycloak url for common hosted CHES
    required: true
  - name: CHES_CLIENT_ID
    description: Client Id to request the access token for connecting to CHES
    required: true
  - name: CHES_CLIENT_SECRET
    description: Client Secret to request the access token for connecting to CHES
    required: true
  - name: CHES_URL
    description: The CHES API url
  - name: NODE_ENV
    description: The NODE Environment
    required: true
  - name: MOTIPAY_API_KEY
    description: API Key for MOTI Pay
    required: true
  - name: MOTIPAY_MERCHANT_ID
    description: Merchant ID for MOTI Pay
    required: true
  - name: MOTIPAY_BASE_URL
    description: Base URL for MOTI Pay
    required: true
  - name: CFS_PRIVATE_KEY
    description: The CFS Private Key For SFTP
  - name: CFS_PASSPHRASE
    description: The CFS Private Key Passphrase For SFTP
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    data:
      database-type: mssql
      database-name: "${DATABASE_NAME}"
      database-host: "${DATABASE_HOST}"
      database-encrypt: "false"
      database-port: "1433"
      auth0-issuer-url: "${AUTH0_ISSUER_URL}"
      auth0-audience: "${AUTH0_AUDIENCE}"
      auth0-ignore-exp: "${AUTH0_IGNORE_EXP}"
      auth0-ignore-exp: "${AUTH0_IGNORE_EXP}"
      dops-cvse-forms-cache-ttl-ms: "${DOPS_CVSE_FORMS_CACHE_TTL_MS}"
      dops-s3-access-type: "${DOPS_S3_ACCESS_TYPE}"
      dops-s3-accesskeyid: "${DOPS_S3_ACCESSKEYID}"
      dops-s3-bucket: "${DOPS_S3_BUCKET}"
      dops-s3-presigned-url-expiry: "${DOPS_S3_PRESIGNED_URL_EXPIRY}"
      dops-s3-endpoint: "${DOPS_S3_ENDPOINT}"
      dops-s3-key: "${DOPS_S3_KEY}"
      node-env: "${NODE_ENV}"
      cdogs-token-url: "${CDOGS_TOKEN_URL}"
      cdogs-url: "${CDOGS_URL}"
      access-api-url: "https://${NAME}-${ZONE}-backend-vehicles.${DOMAIN}"
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    stringData:
      database-user: "${DATABASE_USER}"
      database-password: "${DATABASE_PASSWORD}"
      cdogs-client-id: "${CDOGS_CLIENT_ID}"
      cdogs-client-secret: "${CDOGS_CLIENT_SECRET}"
      dops-s3-secretaccesskey: "${DOPS_S3_SECRETACCESSKEY}"
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          containers:
            - image: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              env:
                - name: DB_TYPE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-type
                - name: MSSQL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-host
                - name: MSSQL_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-port
                - name: MSSQL_DB
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-name
                - name: MSSQL_ENCRYPT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-encrypt
                - name: MSSQL_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-password
                - name: MSSQL_SA_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: database-user
                - name: AUTH0_ISSUER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: auth0-issuer-url
                - name: AUTH0_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: auth0-audience
                - name: AUTH0_IGNORE_EXP
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: auth0-ignore-exp
                - name: DOPS_CVSE_FORMS_CACHE_TTL_MS
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-cvse-forms-cache-ttl-ms
                - name: DOPS_S3_ACCESS_TYPE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-access-type
                - name: DOPS_S3_ACCESSKEYID
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-accesskeyid
                - name: DOPS_S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-bucket
                - name: DOPS_S3_PRESIGNED_URL_EXPIRY
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-presigned-url-expiry  
                - name: DOPS_S3_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-endpoint
                - name: DOPS_S3_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-key
                - name: DOPS_S3_SECRETACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: dops-s3-secretaccesskey
                - name: NODE_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: node-env
                - name: CDOGS_TOKEN_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: cdogs-token-url
                - name: CDOGS_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: cdogs-client-id
                - name: CDOGS_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: cdogs-client-secret
                - name: CDOGS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: cdogs-url
                - name: ACCESS_API_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-${ZONE}-${COMPONENT}
                      key: access-api-url
              ports:
                - containerPort: 5001
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              readinessProbe:
                httpGet:
                  path: /
                  port: 5001
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 15
                timeoutSeconds: 5
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 5001
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 5001-tcp
          protocol: TCP
          port: 80
          targetPort: 5001
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      host: ${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
      port:
        targetPort: 5001-tcp
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: ${NAME}-${ZONE}-${COMPONENT}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
