name: Test Workflow

on:
  workflow_call:
    inputs:
      ### Required
      target:
        description: 'PR number, test or prod.'
        required: true
        type: string

jobs:
  cypress-e2e:
    name: E2E Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: pageLoadTimeout=10000,baseUrl=https://${{ github.event.repository.name }}-${{ inputs.target }}-frontend.apps.silver.devops.gov.bc.ca
          working-directory: ./frontend
          browser: ${{ matrix.browser }}
        env:
          IDIR_LOGIN_URL: ${{vars.IDIR_LOGON_URL}}
          IDIR_USERNAME: ${{secrets.IDIR_USERNAME}}
          IDIR_PASSWORD: ${{secrets.IDIR_PASSWORD}}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./frontend/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
