name: Test Workflow

on:
  pull_request:
  workflow_call:
    inputs:
      ### Required
      target:
        description: 'PR number, test or prod.'
        default: 'test'
        required: true
        type: string

jobs:
  update-term-oversize:
    name: (BCEID) Update Term Oversize 
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tests/
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6.7.7
        name: Cypress run
        env:
          CYPRESS_baseUrl: https://${{ github.event.repository.name }}-${{ inputs.target || 'test' }}-frontend.apps.silver.devops.gov.bc.ca/
          CYPRESS_bceid_username: ${{vars.BCEID_USERNAME}}
          CYPRESS_bceid_password: ${{secrets.BCEID_PASSWORD}}
        with:
          browser: ${{ matrix.browser }}
          config: pageLoadTimeout=10000,video=true
          spec: cypress/e2e/bceid-update-term-oversize.cy.js
          working-directory: tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: tests/cypress/videos/
          overwrite: true
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  
  new-term-oversize:
    name: (BCEID) New Term Oversize 
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tests/
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6.7.7
        name: Cypress run
        env:
          CYPRESS_baseUrl: https://${{ github.event.repository.name }}-${{ inputs.target || 'test' }}-frontend.apps.silver.devops.gov.bc.ca/
          CYPRESS_bceid_username: ${{vars.BCEID_USERNAME}}
          CYPRESS_bceid_password: ${{secrets.BCEID_PASSWORD}}
        with:
          browser: ${{ matrix.browser }}
          config: pageLoadTimeout=10000,video=true
          spec: cypress/e2e/bceid-new-term-oversize.cy.js
          working-directory: tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: tests/cypress/videos/
          overwrite: true
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

  new-term-overweight:
    name: (BCEID) New Term Overweight 
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tests/
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6.7.7
        name: Cypress run
        env:
          CYPRESS_baseUrl: https://${{ github.event.repository.name }}-${{ inputs.target || 'test' }}-frontend.apps.silver.devops.gov.bc.ca/
          CYPRESS_bceid_username: ${{vars.BCEID_USERNAME}}
          CYPRESS_bceid_password: ${{secrets.BCEID_PASSWORD}}
        with:
          browser: ${{ matrix.browser }}
          config: pageLoadTimeout=10000,video=true
          spec: cypress/e2e/bceid-new-term-overweight.cy.js
          working-directory: tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: tests/cypress/videos/
          overwrite: true
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

  idir-update-term-oversize:
      name: (IDIR) Update Term Oversize 
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: tests/
      strategy:
        matrix:
          browser: [chrome, firefox, edge]
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - uses: cypress-io/github-action@v6.7.7
          name: Cypress run
          env:
            CYPRESS_baseUrl: https://${{ github.event.repository.name }}-${{ inputs.target || 'test' }}-frontend.apps.silver.devops.gov.bc.ca/
            CYPRESS_bceid_username: ${{vars.IDIR_USERNAME}}
            CYPRESS_bceid_password: ${{secrets.IDIR_PASSWORD}}
          with:
            browser: ${{ matrix.browser }}
            config: pageLoadTimeout=10000,video=true
            spec: cypress/e2e/idir-amend-term-oversize.cy.js
            working-directory: tests

        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: cypress-screenshots
            path: tests/cypress/screenshots/
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
        
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: cypress-videos
            path: tests/cypress/videos/
            overwrite: true
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

  bceid-crud-vehicles:
      name: (BCEID) Crud vehicles 
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: tests/
      strategy:
        matrix:
          browser: [chrome, firefox, edge]
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - uses: cypress-io/github-action@v6.7.7
          name: Cypress run
          env:
            CYPRESS_baseUrl: https://${{ github.event.repository.name }}-${{ inputs.target || 'test' }}-frontend.apps.silver.devops.gov.bc.ca/
            CYPRESS_bceid_username: ${{vars.BCEID_USERNAME}}
            CYPRESS_bceid_password: ${{secrets.BCEID_PASSWORD}}
          with:
            browser: ${{ matrix.browser }}
            config: pageLoadTimeout=10000,video=true
            spec: cypress/e2e/bceid-crud-vehicles.cy.js
            working-directory: tests

        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: cypress-screenshots
            path: tests/cypress/screenshots/
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
        
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: cypress-videos
            path: tests/cypress/videos/
            overwrite: true
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
