name: Test Workflow

on:
  workflow_call:
    inputs:
      ### Required
      target:
        description: 'PR number, test or prod.'
        required: true
        type: string

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Integration tests
        env:
          API_NAME: nest
          BASE_URL: https://${{ github.event.repository.name }}-${{ inputs.target }}-frontend.apps.silver.devops.gov.bc.ca
        run: |
          cd tests/integration
          npm ci
          node src/main.js

  cypress-e2e:
    name: E2E Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: pageLoadTimeout=10000,baseUrl=https://${{ github.event.repository.name }}-${{ inputs.target }}-frontend.apps.silver.devops.gov.bc.ca,CYPRESS_USERNAME=${{secrets.CYPRESS_USERNAME}},CYPRESS_PASSWORD=${{secrets.CYPRESS_PASSWORD}},CYPRESS_SELECT_VEHICLE=${{vars.CYPRESS_SELECT_VEHICLE}},CYPRESS_PAYBC_URL=${{vars.CYPRESS_PAYBC_URL}},CYPRESS_CC_NUMBER=${{secrets.CYPRESS_CC_NUMBER}},CYPRESS_CC_EXPMONTH=${{secrets.CYPRESS_CC_EXPMONTH}},CYPRESS_CC_EXPYEAR=${{secrets.CYPRESS_CC_EXPYEAR}},CYPRESS_CC_CVD=${{secrets.CYPRESS_CC_CVD}}


          working-directory: ./frontend
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
