name: Deploy Demo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "uat"
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "uat"
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-demo:
    name: Deploys (DEMO)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      environment: demo
      tag: ${{inputs.tag}}
      release: "demo"
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='test' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='demo' \
        --set-string global.pr_num='${{ inputs.tag }}' \
