---
name: Deploy Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
jobs:
  deploy-dev:
    name: Deploys (DEV)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: dev
      release: ${{inputs.tag}}
      tag: ${{ inputs.tag }}
      triggers: '' #omit=always;
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='dev' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='dev' \
        ${{ inputs.params }} \
