---
name: Deploy Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
jobs:
  deploy-dev:
    name: Deploys (DEV)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      environment: dev
      release: ${{inputs.tag}}
      tag: ${{ inputs.tag }}
      triggers: '' #omit=always;
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='dev' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='dev' \
        --set-string global.pr_num='${{ inputs.tag }}' \
        --set-string dops.ingress.enabled='false'
        --set-json dops.containers[0].resources='{"limits": {"cpu": "1000m", "memory": "2000Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json frontend.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json scheduler.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json policy.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json vehicles.containers[0].resources='{"limits": {"cpu": "300m", "memory": "500Mi"}, "requests": {"cpu": "200m", "memory": "400Mi"}}' \
