name: Deploy Prod (Gold)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "prod"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "prod"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string

jobs:
  deploys-prod-gold:
    name: Deploys Prod (Gold)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: gold-prod
      tag: ${{ inputs.tag }}
      release: prod
      params: |
        --set-string global.domain='apps.gold.devops.gov.bc.ca' \
        --set-string global.vault.authPath='auth/k8s-gold' \
        --set-string global.license='c3141c' \
        --set-string global.zone='prod' \
        --set-string global.vault.role='prod' \
        --set-string global.vault.zone='prod' \
        ${{ inputs.params }} \
  
  deploys-prod-golddr:
    name: Deploys Prod (Golddr)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: golddr-prod
      tag: ${{ inputs.tag }}
      release: prod
      params: |
        --set-string global.domain='apps.golddr.devops.gov.bc.ca' \
        --set-string global.vault.authPath='auth/k8s-golddr' \
        --set-string global.license='c3141c' \
        --set-string global.zone='prod' \
        --set-string global.vault.role='prod' \
        --set-string global.vault.zone='prod' \
        ${{ inputs.params }} \
