---
name: Loadtests

on:
  workflow_dispatch:
    inputs:
      ### Required
      num_threads:
        description: 'Number of concurrent threads (USERS) for each test in sequence'
        default: 200
        required: true
        type: integer
      dops_api_url:
        description: 'The url endpoint for the dops'
        default: onroutebc-test-dops.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      frontend_api_url:
        description: 'The url endpoint for the frontend'
        default: onroutebc-test-frontend.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      vehicles_api_url:
        description: 'The url endpoint for vehicles'
        default: onroutebc-test-vehicles.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      bearer_token:
        description: "The bearer token pertaining to the user running the tests"
        required: true
        type: string

jobs:
  loadtests:
    name: Loadtests
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: loadtests/dops/orbc_load_test_plan_dops.jmx
          outputReportsFolder: results_dops
          args: |
            --loglevel INFO 
            --jmeterlogconf=log.conf
            -JBEARER_TOKEN=${{inputs.bearer_token}}
            -JNUM_THREADS=${{inputs.num_threads}}
            -JFRONTEND_API_URL=${{inputs.frontend_api_url}}
            -JDOPS_API_URL=${{inputs.dops_api_url}}
            -JVEHICLES_API_URL=${{inputs.vehicles_api_url}}
            -JRESULTS_DIR=results_dops
      
      - uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: loadtests/vehicles/orbc_load_test_plan_vehicles.jmx
          outputReportsFolder: results_vehicles
          args: |
            --loglevel INFO 
            --jmeterlogconf=log.conf
            -JBEARER_TOKEN=${{inputs.bearer_token}}
            -JNUM_THREADS=${{inputs.num_threads}}
            -JFRONTEND_API_URL=${{inputs.frontend_api_url}}
            -JDOPS_API_URL=${{inputs.dops_api_url}}
            -JVEHICLES_API_URL=${{inputs.vehicles_api_url}}
            -JRESULTS_DIR=results_vehicles
      
      - uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: loadtests/frontend/orbc_load_test_plan_frontend.jmx
          outputReportsFolder: results_frontend
          args: |
            --loglevel INFO 
            --jmeterlogconf=log.conf
            -JBEARER_TOKEN=${{inputs.bearer_token}}
            -JNUM_THREADS=${{inputs.num_threads}}
            -JFRONTEND_API_URL=${{inputs.frontend_api_url}}
            -JDOPS_API_URL=${{inputs.dops_api_url}}
            -JVEHICLES_API_URL=${{inputs.vehicles_api_url}}
            -JRESULTS_DIR=results_frontend

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results-dops
          path: results_dops

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results-vehicles
          path: results_vehicles
      
      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results-frontend
          path: results_frontend
