---
name: Loadtests

on:
  workflow_dispatch:
    inputs:
      ### Required
      dops_api_url:
        description: 'The url endpoint for the dops'
        default: onroutebc-test-dops.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      frontend_api_url:
        description: 'The url endpoint for the frontend'
        default: onroutebc-test-frontend.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      vehicles_api_url:
        description: 'The url endpoint for vehicles'
        default: onroutebc-test-vehicles.apps.silver.devops.gov.bc.ca
        required: true
        type: string
      bearer_token:
        description: "The bearer token pertaining to the user running the tests"
        required: true
        type: string

jobs:
  loadtests:
    name: Loadtests
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Run All JMeter Tests In tests Folder
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: loadtests
          outputReportsFolder: results
          args: |
            --loglevel INFO 
            --jmeterlogconf=log.conf
            -JBEARER_TOKEN=${{inputs.bearer_token}}
            -JDOPS_API_URL=${{inputs.dops_api_url}}
            -JFRONTEND_API_URL=${{inputs.frontend_api_url}}
            -JVEHICLES_API_URL=${{inputs.vehicles_api_url}}
            -JRESULTS_DIR=loadtests/results

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results
          path: loadtests/results/

