---
name: Loadtests

on:
  workflow_call:
    inputs:
      ### Required
      args:
        description: 'List of args to feed jmeter'
        required: true
        type: string
      environment:
        description: "Deployment environment - dev/test/prod"
        required: true
        type: string
        default: "dev"

jobs:
  loadtests:
    name: Loadtests
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Run All JMeter Tests In tests Folder
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ${{inputs.package}}/test/load_tests
          outputReportsFolder: results
          args: |
            --loglevel INFO \
            -JBEARER_TOKEN=${{secrets.ORBC_ACCESS_TOKEN}} \
            ${{inputs.args}}

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results
          path: results/

