name: Merge

on:
  workflow_run:
    workflows: [PR Closed]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys-test:
    name: Deploys (test)
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: test
      values: values.yaml
      license: c28f0c
      vault_role: nonprod
      zone: dev

  integration-e2e:
    name: Integration and E2E Tests
    needs: [deploys-test]
    uses: ./.github/workflows/.tests.yml
    with:
      target: test

  deploys-prod:
    name: Deploys (prod)
    needs: [integration-e2e]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: prod
      values: values.yaml
