name: Merge

on:
  workflow_run:
    workflows: [PR Closed]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys-test:
    name: Deploys (test)
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: test
      target: latest
      values: values.yaml
      license: c28f0c
      vault_role: nonprod
      zone: test

#  integration-e2e:
#    name: Integration and E2E Tests
#    needs: [deploys-test]
#    uses: ./.github/workflows/.tests.yml
#    with:
#      target: test
  
  promote-images-test:
    name: Promote Images - Test
    #needs: [deploys-test, integration-e2e]
    needs: [deploys-test]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: latest
          tags: test
  
  deploys-prod:
    name: Deploys (prod)
    needs: [promote-images-test]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: prod
      target: test
      values: values.yaml
      license: c28f0c
      vault_role: prod
      zone: prod
  
  promote-images-prod:
    name: Promote Images - Prod
    needs: [deploys-prod]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: prod  #Promote images AFTER successful deploy
