name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'common/graphics/**'
      - '!.github/workflows/deploy.yml'
      - '!.github/workflows/merge.yml'
  workflow_dispatch:
    inputs:
      pr:
        description: "PR num of image to deploy"
        required: false
        type: string


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        if: ${{ github.event_name == 'push' }}
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1
      - name: PR Number
        if: ${{ github.event_name != 'push' }} 
        id: pr
        run: echo ${{inputs.pr}} >> $GITHUB_OUTPUT

  deploys-test:
    name: Deploys (Test)
    needs: [vars]
    uses: ./.github/workflows/uat.yml
    secrets: inherit
    with:
      tag: ${{ needs.vars.outputs.pr }}

  promote-images-test:
    name: Promote Images - Test
    needs: [deploys-test, vars]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, scheduler, policy]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.pr }}
          tags: test  #Promote images AFTER successful deploy

  release-please:
    name: Release-Please
    needs: [promote-images-test, vars]
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          changelog-types: '[{"type":"ORV2","section":"Features","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"build","section":"Miscellaneous","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"ci","section":"Miscellaneous","hidden":false},{"type":"docs","section":"Miscellaneous","hidden":false},{"type":"perf","section":"Miscellaneous","hidden":false},{"type":"refactor","section":"Miscellaneous","hidden":false},{"type":"revert","section":"Miscellaneous","hidden":false},{"type":"style","section":"Miscellaneous","hidden":false},{"type":"test","section":"Miscellaneous","hidden":false}]'
