name: Notifications
on:
  workflow_run: 
    workflows: [PR,Merge]
    types:
      - in_progess
      - completed  
jobs:
  notify-teams-in-progress:
    runs-on: ubuntu-22.04
    steps:
      - uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: |
            Workflow:  ${{github.event.workflow}}
            Status: ${{github.event.type}}
          notification-color: 17a2b8
          timezone: America/Vancouver
  notify-teams-complete:
    runs-on: ubuntu-22.04
    steps:
      - uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: |
            Workflow:  ${{github.event.workflow}}
            Status: ${{github.event.type}}
          notification-color: 28a745
          timezone: America/Vancouver
