
name: Notifications

on:
  workflow_run: 
    workflows: [Analysis] #why this not triggering?
jobs:
  notify-teams:
    name: Notify Teams 
    needs: [vars]
    runs-on: ubuntu-22.04
    steps:
      - name: MS Teams Notifications
        uses: dchourasia/ms-teams-notification@1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          show-on-failure: true
