
name: Notifications

on:
  workflow_run: 
    workflows: [Analysis] #why this not triggering?
jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  notify-teams:
    name: Notify Teams 
    needs: [vars]
    runs-on: ubuntu-22.04
    steps:
      - name: MS Teams Notifications
        uses: dchourasia/ms-teams-notification@1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          custom-facts: |
            - name: Notify Teams
              value: "PR# ${{ needs.vars.outputs.pr }}"
          show-on-failure: true
