name: Notifications
on:
  workflow_run: 
    workflows: [PR,Merge]
    types:
      - in_progess
      - completed  
jobs:
  notify-teams-in-progress:
    if: ${{github.action != 'completed'}}
    runs-on: ubuntu-22.04
    steps:
      - uses: simbo/msteams-message-card-action@latest
        with:
          webhook: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          title: ${{github.event.workflow_run.pull_requests[0].number}}
          message: ${{github.event.workflow_run.head_commit.message}} 
          color: ff69b4
          buttons: |
            PR ${{github.event.workflow_run.pull_requests[0].number}} https://github.com/bcgov/onroutebc/pull/${{github.event.workflow_run.pull_requests[0].number}}
            Diff https://github.com/bcgov/onroutebc/pull/${{github.event.workflow_run.pull_requests[0].number}}/files
          sections: |
            -
              activityTitle: ${{github.event.workflow_run.head_commit.committer.name}}
              activitySubtitle: ${{github.event.workflow_run.head_commit.committer.date}}
              activityImage: https://github.com${{github.event.workflow_run.head_commit.committer.username}}.png
              text: in_progress
  notify-teams-completed:
    if: ${{github.action == 'completed'}}
    runs-on: ubuntu-22.04
    steps:
      - uses: simbo/msteams-message-card-action@latest
        with:
          webhook: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          title: ${{github.event.workflow_run.pull_requests[0].number}}
          message: ${{github.event.workflow_run.head_commit.message}} 
          color: 28a745
          buttons: |
            PR ${{github.event.workflow_run.pull_requests[0].number}} https://github.com/bcgov/onroutebc/pull/${{github.event.workflow_run.pull_requests[0].number}}
            Diff https://github.com/bcgov/onroutebc/pull/${{github.event.workflow_run.pull_requests[0].number}}/files
          sections: |
            -
              activityTitle: ${{github.event.workflow_run.head_commit.committer.name}}
              activitySubtitle: ${{github.event.workflow_run.head_commit.committer.date}}
              activityImage: https://github.com${{github.event.workflow_run.head_commit.committer.username}}.png
              facts:
                - name: "Pull Requests"
                  value: ${{toJSON(github.event.workflow_run.pull_requests)}}
                - name: "Event "
                  value: ${{toJSON(github.event)}}
              text: completed
