name: PR

on:
  pull_request:
  merge_group:

concurrency:
  # Cancel in progress for PR open and close, but not merge_group
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-description-add:
    name: PR Description Add
    if: github.event_name == 'pull_request'
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    timeout-minutes: 1
    steps:
      - uses: bcgov-nr/action-pr-description-add@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Deployments, as required, will be available below:
            - [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }})
            - [Vehicles](https://${{ env.PREFIX }}-vehicles.${{ env.DOMAIN }}/api)
            - [Dops](https://${{ env.PREFIX }}-dops.${{ env.DOMAIN }}/api)
            - [Policy](https://${{ env.PREFIX }}-policy.${{ env.DOMAIN }}/api)
            - [Scheduler](https://${{ env.PREFIX }}-scheduler.${{ env.DOMAIN }}/api)

            Please create PRs in draft mode.  Mark as ready to enable:
            - [Analysis Workflow](https://github.com/${{ github.repository }}/actions/workflows/analysis.yml)

            After merge, new images are promoted to:
            - [Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml)

  # Get PR number for merge queues, otherwise jusr use github.event.nuber
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-22.04
    steps:
      - name: PR Number
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    needs: [vars]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, scheduler, policy]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          #keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ needs.vars.outputs.pr }}
          tag_fallback: latest
          triggers: '${{ matrix.package }}/' #omit to build everything

  # https://github.com/bcgov-nr/action-deployer-openshift
  deploys:
    name: Deploys
    needs: [builds, vars]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      repository: ${{ github.event.repository.name }}
      environment: dev
      release: ${{ needs.vars.outputs.pr }}
      tag: ${{ needs.vars.outputs.pr }}
      triggers: '' #omit=always;
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='dev' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='dev' \
        --set-string global.pr_num='${{ needs.vars.outputs.pr }}' \
        --set-json dops.containers[0].resources='{"limits": {"cpu": "1000m", "memory": "2000Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json frontend.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json scheduler.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json policy.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json vehicles.containers[0].resources='{"limits": {"cpu": "300m", "memory": "500Mi"}, "requests": {"cpu": "200m", "memory": "400Mi"}}' \

  
  loadtests:
    name: Loadtests
    needs: [deploys]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/workflows/.loadtest.yaml
        with:
          environment: dev
          target: ${{ github.event.number }}

  results:
    name: PR Results
    if: always() && !failure()
    needs: [loadtests]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Workflow completed successfully!"
                                                                                                                                                 
