name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-greeting:
    name: PR Greeting
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: PR Greeting
        uses: bcgov-nr/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [Backend - Vehicles](https://${{ env.PREFIX }}-backend-vehicles.${{ env.DOMAIN }}/) available
            [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  builds:
    name: Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend/vehicles, frontend]
        include:
          - package: backend/vehicles
            triggers: ('backend/vehicles/')
          - package: frontend
            triggers: ('frontend/')
    steps:
      - uses: actions/checkout@v3

      - uses: bcgov-nr/action-builder-ghcr@v1.1.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}
    
      - name: Get package.json version
        shell: bash
        run: echo PACKAGE_VERSION=$(curl https://raw.githubusercontent.com/bcgov/onroutebc/main/${{matrix.package}}/package.json | grep \"version\" | awk -F ':' '{print($2)}' | awk -F ',' '{print($1)}' | awk -F '"' '{print($2)}') | tee $GITHUB_ENV

      - name: Check if build image already exists
        shell: bash
        run: | 
          TOKEN=$(curl -s https://ghcr.io/token\?scope\="repository:${{ github.repository }}/${{ matrix.package }}:pull" | jq -r .token)
          URL="https://ghcr.io/v2/${{ github.repository }}/${{ matrix.package }}/manifests/${{ env.PACKAGE_VERSION }}"
          if [ $(curl -ILso /dev/null -w "%{http_code}" -H "Authorization: Bearer ${TOKEN}" "${URL}") -e 200 ] 
          then
            exit 1
          fi

      - name: Tag Images with package.json version 
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.component }}
          target: test
          tags: ${{ env.PACKAGE_VERSION }} 

  deploys:
    name: Deploys
    needs:
      - builds
    runs-on: ubuntu-22.04
    environment: dev
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        name: [init, backend/vehicles, frontend]
        include:
          - name: backend/vehicles
            file: backend/vehicles/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: init
            file: common/openshift.init.yml
            overwrite: false
    steps:
      - name: Get Vault Environment
        shell: bash
        run: echo VAULT_ENV=${{secrets.OC_NAMESPACE}} | awk -F '-' '{print($2!="prod")?$1"-nonprod":$1"-prod"}' | tee $GITHUB_ENV
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.developer.gov.bc.ca
          token: ${{ secrets.VAULT_TOKEN }}
          exportEnv: 'false'
          namespace: platform-services
          secrets: |
            ${{env.VAULT_ENV}}/data/database-dev  DATABASE_HOST     | VAULT_DATABASE_HOST;
            ${{env.VAULT_ENV}}/data/database-dev  DATABASE_USER     | VAULT_DATABASE_USER;
            ${{env.VAULT_ENV}}/data/database-dev  DATABASE_NAME     | VAULT_DATABASE_NAME;
            ${{env.VAULT_ENV}}/data/database-dev  DATABASE_PASSWORD | VAULT_DATABASE_PASSWORD;
            ${{env.VAULT_ENV}}/data/database-dev  DATABASE_PORT     | VAULT_DATABASE_PORT
      - name: Deploy Application
        uses: bcgov-nr/action-deployer-openshift@v1.0.3
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: false
          parameters:
            -p ZONE=${{ github.event.number }}
            -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }} 
            -p DATABASE_NAME=${{steps.secrets.outputs.VAULT_DATABASE_NAME}}
            -p DATABASE_USER=${{steps.secrets.outputs.VAULT_DATABASE_USER}}
            -p DATABASE_PASSWORD=${{steps.secrets.outputs.VAULT_DATABASE_PASSWORD}}
            -p DATABASE_HOST=${{steps.secrets.outputs.VAULT_DATABASE_HOST}}
            ${{ matrix.parameters }}
