name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-greeting:
    name: PR Greeting
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: PR Greeting
        uses: bcgov-nr/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [Backend - Vehicles](https://${{ env.PREFIX }}-backend-vehicles.${{ env.DOMAIN }}/) available
            [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  secrets:
    name: Get Secrets
    runs-on: ubuntu-22.04
    environment: dev
    strategy:
      max-parallel: 1
      fail-fast: true
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2 
        with:
          url: https://vault.developer.gov.bc.ca
          token: ${{ secrets.VAULT_TOKEN }}
          exportEnv: 'false'
          namespace: platform-services
          secrets: |
            ${{secrets.VAULT_ENV}}/data/database-dev  DATABASE_HOST               | VAULT_DATABASE_HOST;
            ${{secrets.VAULT_ENV}}/data/database-dev  DATABASE_USER               | VAULT_DATABASE_USER;
            ${{secrets.VAULT_ENV}}/data/database-dev  DATABASE_NAME               | VAULT_DATABASE_NAME;
            ${{secrets.VAULT_ENV}}/data/database-dev  DATABASE_PASSWORD           | VAULT_DATABASE_PASSWORD;
            ${{secrets.VAULT_ENV}}/data/database-dev  DATABASE_PORT               | VAULT_DATABASE_PORT;
            ${{secrets.VAULT_ENV}}/data/coms-dev  BASICAUTH_PASSWORD              | VAULT_BASICAUTH_PASSWORD;
            ${{secrets.VAULT_ENV}}/data/coms-dev  BASICAUTH_USERNAME              | VAULT_BASICAUTH_USERNAME;
            ${{secrets.VAULT_ENV}}/data/coms-dev  OBJECTSTORAGE_ACCESSKEYID       | VAULT_OBJECTSTORAGE_ACCESSKEYID;
            ${{secrets.VAULT_ENV}}/data/coms-dev  OBJECTSTORAGE_BUCKET            | VAULT_OBJECTSTORAGE_BUCKET;
            ${{secrets.VAULT_ENV}}/data/coms-dev  OBJECTSTORAGE_ENDPOINT          | VAULT_OBJECTSTORAGE_ENDPOINT;
            ${{secrets.VAULT_ENV}}/data/coms-dev  OBJECTSTORAGE_KEY               | VAULT_OBJECTSTORAGE_KEY;
            ${{secrets.VAULT_ENV}}/data/coms-dev  OBJECTSTORAGE_SECRETACCESSKEY   | VAULT_OBJECTSTORAGE_SECRETACCESSKEY
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend/vehicles, frontend]
        include:
          - package: backend/vehicles
            triggers: ('backend/vehicles/')
          - package: frontend
            triggers: ('frontend/')
    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-builder-ghcr@v1.1.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}

  deploys:
    name: Deploys
    needs:
      - builds
      - secrets
    runs-on: ubuntu-22.04
    environment: dev
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        name: [init, backend/vehicles, frontend]
        include:
          - name: backend/vehicles
            file: backend/vehicles/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: init
            file: common/openshift.init.yml
            overwrite: false
    steps:
      - name: Deploy Application
        uses: bcgov-nr/action-deployer-openshift@v1.0.3
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: false
          parameters:
            -p ZONE=${{ github.event.number }}
            -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }} 
            -p DATABASE_NAME=${{env.VAULT_DATABASE_NAME}}
            -p DATABASE_USER=${{env.VAULT_DATABASE_USER}}
            -p DATABASE_PASSWORD=${{env.VAULT_DATABASE_PASSWORD}}
            -p DATABASE_HOST=${{env.VAULT_DATABASE_HOST}}
            ${{ matrix.parameters }}

  helm-deploys:
    name: Helm Deploys
    needs:
      - builds
      - secrets
    runs-on: ubuntu-22.04
    environment: dev
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        name: [common-object-storage-managment]
        include:
          - release: ${{ github.event.repository.name }}-${{ github.event.number }}-common-object-management-service
            chart: common-object-management-service
            repo: https://bcgov.github.io/common-object-management-service
            repo-alias: common-object-management-service
            values: |
              fullNameOverride: ${{ github.event.repository.name }}-${{ github.event.number }}-common-object-management-service
              route.host: ${{ github.event.repository.name }}-${{ github.event.number }}-coms.apps.silver.devops.gov.bc.ca
              basicAuthSecretOverride.username: ${{env.VAULT_BASICAUTH_USERNAME}}
              objectStorageSecretOverride.username: ${{env.VAULT_OBJECTSTORAGE_ACCESSKEYID}}
              objectStorageSecretOverride.password: ${{env.VAULT_OBJECTSTORAGE_SECRETACCESSKEY}}
              features.oidcAuth: false
              config.enabled: true
              config.releaseScoped: true
              config.configMap.KC_IDENTITYKEY: null
              config.configMap.KC_PUBLICKEY: null
              config.configMap.KC_REALM: null
              config.configMap.KC_SERVERURL: null
              config.configMap.OBJECTSTORAGE_BUCKET: ${{env.VAULT_OBJECTSTORAGE_BUCKET}}
              config.configMap.OBJECTSTORAGE_ENDPOINT: ${{env.VAULT_OBJECTSTORAGE_ENDPOINT}}
              config.configMap.OBJECTSTORAGE_KEY: ${{env.VAULT_OBJECTSTORAGE_KEY}}
    steps:
      - name: Helm Deploy
        uses: vimeda/helm@v1.6.8
        with:
          namespace: ${{ secrets.OC_NAMESPACE}}
          release: ${{matrix.release}}
          chart: ${{ matrix.chart }}
          token: ${{ secrets.OC_TOKEN }}
          repo: ${{matrix.repo}}
          repo-alias: ${{matrix.repo-alias}}
          values: ${{ matrix.values }}
          env:
            KUBECONFIG_FILE: ${{secrets.KUBECONFIG_FILE}}
