name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, tps-migration]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: '${{ matrix.package }}/' #omit to build everything

  # https://github.com/bcgov-nr/action-deployer-openshift
  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      repository: ${{ github.event.repository.name }}
      environment: dev
      release: ${{ github.event.number }}
      tag: ${{ github.event.number }}
      triggers: '' #omit=always;
      vault_role: nonprod
      vault_zone: dev
      params: |
        --set-json dops.containers[0].resources='{"limits": {"cpu": "2000m", "memory": "3000Mi"}, "requests": {"cpu": "1000m", "memory": "2000Mi"}}' \
        --set-json frontend.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json tps-migration.containers[0].resources='{"limits": {"cpu": "75m", "memory": "150Mi"}, "requests": {"cpu": "25m", "memory": "50Mi"}}' \
        --set-json vehicles.containers[0].resources='{"limits": {"cpu": "300m", "memory": "500Mi"}, "requests": {"cpu": "200m", "memory": "400Mi"}}' \
