name: Deploy Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "prod"
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "prod"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys-prod:
    name: Deploys (prod)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: prod
      tag: ${{ inputs.tag }}
      release: prod
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='prod' \
        --set-string global.vault.role='prod' \
        --set-string global.vault.zone='prod' \
        --set-string global.pr_num='${{ inputs.tag }}' \
