---
name: Regression Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ### Required
      release:
        description: 'PR number, test or prod.'
        default: test
        required: true
        type: string
      username:
        description: 'username of test account to use'
        default: ''
        required: true
        type: string
      password:
        description: 'password of test account to use'
        default: ''
        required: true
        type: string


jobs:
  vars:
    name: Set Variables
    outputs:
      dops_api_url: ${{ steps.vars.outputs.dops_api_url }}
      frontend_api_url: ${{ steps.vars.outputs.frontend_api_url }}
      vehicles_api_url: ${{ steps.vars.outputs.vehicles_api_url }}
      environment: ${{ steps.vars.outputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: vars
        id: vars
        run: |
          echo "dops_api_url=onroutebc-${{inputs.release}}-dops.apps.silver.devops.gov.bc.ca" >> GITHUB_ENV
          echo "frontend_api_url=onroutebc-${{inputs.release}}-frontend.apps.silver.devops.gov.bc.ca" >> GITHUB_ENV
          echo "vehicles_api_url=onroutebc-${{inputs.release}}-vehicles.apps.silver.devops.gov.bc.ca" >> GITHUB_ENV
          echo "environment=${{inputs.release || 'dev'}}" >> GITHUB_ENV 
  
  amend_term_oversize:
    name: Amend Term Oversize
    needs: [ vars ]
    environment: ${{ needs.vars.outputs.environment }}
    secrets: inherit
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-chromedriver@v2
      - uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/regression/orbc_load_test_plan_frontend_amend_term_oversize.jmx
          outputReportsFolder: tests/regression/results
          plugins: "jpgc-webdriver"
          args: |
            --loglevel INFO 
            --jmeterlogconf=log.conf
            -JFRONTEND_API_URL=${{needs.vars.outputs.frontend_api_url}}
            -JRESULTS_DIR=tests/regression/results/
            -JUSER=${{vars.BCEID_USER}}
            -JPASSWORD=${{secrets.BCEID_PASSWORD}}

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: jmeter-test-results-frontend
          path: tests/regression/results 
