---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  vars:
    name: Set Variables
    outputs:
      release-name: ${{ steps.release-name.outputs.release-name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Release Name
        id: release-name
        run: |
          echo release-name=$(curl https://api.github.com/repos/bcgov/onroutebc/releases/latest | jq -r .tag_name) >> $GITHUB_OUTPUT
  promote-images-release:
    name: Promote Images - Release
    needs: [vars]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, scheduler, policy]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: ${{ needs.vars.outputs.release-name }}

  deploys-uat:
    name: Deploys (Uat)
    needs: [vars,promote-images-release]
    uses: ./.github/workflows/uat.yml
    secrets: inherit
    with:
      tag: ${{ needs.vars.outputs.release-name }}
  
  promote-images-uat:
    name: Promote Images - Uat
    needs: [vars,deploys-uat]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, scheduler, policy]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.release-name }}
          tags: uat
  
  deploys-prod:
    name: Deploys (Prod)
    needs: [vars,promote-images-uat]
    uses: ./.github/workflows/prod.yml
    secrets: inherit
    with:
      tag: ${{ needs.vars.outputs.release-name }}
  
  promote-images-prod:
    name: Promote Images - Prod
    needs: [vars,deploys-prod]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [dops, vehicles, frontend, scheduler, policy]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: uat
          tags: prod
