
name: release-please

on:
  push:
    branches: [main]
    paths-ignore:
      - '.release-please-manifest.json'
      - '*.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4.0.2
        with:
          config-file: .github/release-please-config.json

