---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  vars:
    name: Set Variables
    outputs:
      release-name: ${{ steps.release-name.outputs.release-name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Release Name
        id: release-name
        run: |
          echo release-name=$(curl https://api.github.com/repos/bcgov/onroutebc/releases/latest | jq -r .tag_name)

  deploys-uat:
    name: Deploys (uat)
    needs: [vars]
    uses: ./.github/workflows/uat.yml
    secrets: inherit
    with:
      environment: test
      tag: ${{ needs.vars.outputs.release-name }}
  
  deploys-prod:
    name: Deploys (prod)
    needs: [deploys-uat, vars]
    uses: ./.github/workflows/prod.yml
    secrets: inherit
    with:
      environment: prod
      tag: ${{ needs.vars.outputs.release-name }}
