---
name: Deploy UAT (Silver)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "test"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "test"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  
jobs:
  deploy-uat-silver:
    name: Deploys UAT (Silver)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: uat
      tag: ${{inputs.tag}}
      release: uat
      params: |
        --set-string global.domain='apps.silver.devops.gov.bc.ca' \
        --set-string global.vault.authPath='auth/k8s-silver' \
        --set-string global.license='c28f0c' \
        --set-string global.zone='test' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='uat' \
        ${{ inputs.params }} \
