---
name: Deploy UAT

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "test"
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "test"
  

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-uat:
    name: Deploys (UAT)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      autoscaling: true
      environment: test
      tag: ${{inputs.tag}}
      release: uat
      params: |
        --set-string global.license='c28f0c' \
        --set-string global.zone='test' \
        --set-string global.vault.role='nonprod' \
        --set-string global.vault.zone='uat' \
        --set-string global.pr_num='${{ inputs.tag }}' \
